insert into TagMap (GSIName, TagPath, DataType) values ('VMJ132Z3-1', 'SFC IO/Drier Regeneration/VMJ132Z3-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128C-REGEN-TIME', 'SFC IO/Drier Regeneration/VMJ132Z3-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMJ132Z2-1', 'SFC IO/Drier Regeneration/VMJ132Z2-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128B-REGEN-TIME', 'SFC IO/Drier Regeneration/VMJ132Z2-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMJ132Z1-1', 'SFC IO/Drier Regeneration/VMJ132Z1-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128A-REGEN-TIME', 'SFC IO/Drier Regeneration/VMJ132Z1-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS702', 'SFC IO/Drier Regeneration/VMS702','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-PE124B-DC-MODEATTR', 'SFC IO/Drier Regeneration/VMS702','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS701', 'SFC IO/Drier Regeneration/VMS701','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-PE124A-DC-MODEATTR', 'SFC IO/Drier Regeneration/VMS701','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR806', 'SFC IO/Drier Regeneration/VMR806','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-DRIER-OUT-ROV-DC-MODEATTR', 'SFC IO/Drier Regeneration/VMR806','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR803', 'SFC IO/Drier Regeneration/VMR803','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-BYPASS-ROV-DC-MODEATTR', 'SFC IO/Drier Regeneration/VMR803','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR802', 'SFC IO/Drier Regeneration/VMR802','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-OUT-ROV-DC-MODEATTR', 'SFC IO/Drier Regeneration/VMR802','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR801', 'SFC IO/Drier Regeneration/VMR801','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-IN-ROV-DC-MODEATTR', 'SFC IO/Drier Regeneration/VMR801','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMP130', 'SFC IO/Drier Regeneration/DR-VMP130','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMR107-MODE', 'SFC IO/Drier Regeneration/DR-VMR107-MODE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMT125-MODE', 'SFC IO/Drier Regeneration/DR-VMT125-MODE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS130ME-1', 'SFC IO/Drier Regeneration/VMS130ME-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128C-ACT', 'SFC IO/Drier Regeneration/VMS130ME-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS130ME', 'SFC IO/Drier Regeneration/VMS130ME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128C-REQ', 'SFC IO/Drier Regeneration/VMS130ME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS129ME-1', 'SFC IO/Drier Regeneration/VMS129ME-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128B-ACT', 'SFC IO/Drier Regeneration/VMS129ME-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS129ME', 'SFC IO/Drier Regeneration/VMS129ME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128B-REQ', 'SFC IO/Drier Regeneration/VMS129ME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS128ME-1', 'SFC IO/Drier Regeneration/VMS128ME-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128A-ACT', 'SFC IO/Drier Regeneration/VMS128ME-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS128ME', 'SFC IO/Drier Regeneration/VMS128ME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128A-REQ', 'SFC IO/Drier Regeneration/VMS128ME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS702X-1', 'SFC IO/Drier Regeneration/VMS702X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-PE124B-PV', 'SFC IO/Drier Regeneration/VMS702X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS702X', 'SFC IO/Drier Regeneration/VMS702X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-PE124B-CMD', 'SFC IO/Drier Regeneration/VMS702X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS701X-1', 'SFC IO/Drier Regeneration/VMS701X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-PE124A-PV', 'SFC IO/Drier Regeneration/VMS701X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMS701X', 'SFC IO/Drier Regeneration/VMS701X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-PE124A-CMD', 'SFC IO/Drier Regeneration/VMS701X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR806X-1', 'SFC IO/Drier Regeneration/VMR806X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-DRIER-OUT-ROV-PV', 'SFC IO/Drier Regeneration/VMR806X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR806X', 'SFC IO/Drier Regeneration/VMR806X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-DRIER-OUT-ROV-CMD', 'SFC IO/Drier Regeneration/VMR806X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR803X-1', 'SFC IO/Drier Regeneration/VMR803X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-BYPASS-ROV-PV', 'SFC IO/Drier Regeneration/VMR803X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR803X', 'SFC IO/Drier Regeneration/VMR803X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-BYPASS-ROV-CMD', 'SFC IO/Drier Regeneration/VMR803X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR802X-1', 'SFC IO/Drier Regeneration/VMR802X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-OUT-ROV-PV', 'SFC IO/Drier Regeneration/VMR802X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR802X', 'SFC IO/Drier Regeneration/VMR802X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-OUT-ROV-CMD', 'SFC IO/Drier Regeneration/VMR802X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR801X-1', 'SFC IO/Drier Regeneration/VMR801X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-IN-ROV-PV', 'SFC IO/Drier Regeneration/VMR801X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMR801X', 'SFC IO/Drier Regeneration/VMR801X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-HEATER-IN-ROV-CMD', 'SFC IO/Drier Regeneration/VMR801X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMP102', 'SFC IO/Drier Regeneration/DR-VMP102','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMT125-OP', 'SFC IO/Drier Regeneration/DR-VMT125-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMR107-OP', 'SFC IO/Drier Regeneration/DR-VMR107-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMF829FC', 'SFC IO/Drier Regeneration/VMF829FC','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMF829', 'SFC IO/Drier Regeneration/VMF829FC','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMF829Z', 'SFC IO/Drier Regeneration/VMF829Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMC829', 'SFC IO/Drier Regeneration/VMF829Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMP130Z', 'SFC IO/Drier Regeneration/VMP130Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMC162', 'SFC IO/Drier Regeneration/VMP130Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VME102Z', 'SFC IO/Drier Regeneration/VME102Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMC103', 'SFC IO/Drier Regeneration/VME102Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMP102LS', 'SFC IO/Drier Regeneration/VMP102LS','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMC102', 'SFC IO/Drier Regeneration/VMP102LS','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMJ132Z3', 'SFC IO/Drier Regeneration/VMJ132Z3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128C-REGEN-TIME-IN', 'SFC IO/Drier Regeneration/VMJ132Z3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMJ132Z2', 'SFC IO/Drier Regeneration/VMJ132Z2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128B-REGEN-TIME-IN', 'SFC IO/Drier Regeneration/VMJ132Z2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMJ132Z1', 'SFC IO/Drier Regeneration/VMJ132Z1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-D128A-REGEN-TIME-IN', 'SFC IO/Drier Regeneration/VMJ132Z1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMT124', 'SFC IO/Drier Regeneration/DR-VMT124','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VMT823', 'SFC IO/Drier Regeneration/DR-VMT823','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VME125', 'SFC IO/Drier Regeneration/DR-VME125','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VME124', 'SFC IO/Drier Regeneration/DR-VME124','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VME123', 'SFC IO/Drier Regeneration/DR-VME123','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VME103', 'SFC IO/Drier Regeneration/DR-VME103','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('DR-VME102', 'SFC IO/Drier Regeneration/DR-VME102','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG631Z-1', 'SFC IO/Flying Switch/VRG631Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-C3STRM_C2', 'SFC IO/Flying Switch/VRG631Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG633Z-1', 'SFC IO/Flying Switch/VRG633Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-C3STRM_C3', 'SFC IO/Flying Switch/VRG633Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRA637Z-1', 'SFC IO/Flying Switch/VRA637Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-C3STRM_C3O', 'SFC IO/Flying Switch/VRA637Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRA632Z-1', 'SFC IO/Flying Switch/VRA632Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-C3STRM_C2O', 'SFC IO/Flying Switch/VRA632Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF000R-4', 'SFC IO/Flying Switch/VCF000R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R1-V-C2', 'SFC IO/Flying Switch/VCF000R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF209R-4', 'SFC IO/Flying Switch/VRF209R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R2-C9-C2', 'SFC IO/Flying Switch/VRF209R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF503R-5', 'SFC IO/Flying Switch/VRF503R-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R2-C3-C2', 'SFC IO/Flying Switch/VRF503R-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF502RP-3', 'SFC IO/Flying Switch/VRF502RP-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R2-C2', 'SFC IO/Flying Switch/VRF502RP-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF502Z-2', 'SFC IO/Flying Switch/VRF502Z-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R1-AL-V', 'SFC IO/Flying Switch/VRF502Z-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF9101Z-1', 'SFC IO/Flying Switch/VRF9101Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S-FS-POLY-RATE', 'SFC IO/Flying Switch/VRF9101Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF211R-5', 'SFC IO/Flying Switch/VCF211R-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R1-NH3-V', 'SFC IO/Flying Switch/VCF211R-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF409R-4', 'SFC IO/Flying Switch/VRF409R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R1-C9-TO-C2', 'SFC IO/Flying Switch/VRF409R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF006-5', 'SFC IO/Flying Switch/VRF006-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R1-C6', 'SFC IO/Flying Switch/VRF006-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF403R-4', 'SFC IO/Flying Switch/VRF403R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R1-C3-C2', 'SFC IO/Flying Switch/VRF403R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF402RP-3', 'SFC IO/Flying Switch/VRF402RP-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R1-C2', 'SFC IO/Flying Switch/VRF402RP-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF120R-4', 'SFC IO/Flying Switch/VCF120R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('FS-R1-H2-V', 'SFC IO/Flying Switch/VCF120R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF212Z1', 'SFC IO/Fast Scan Data/VCF212Z1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VAN-SWP', 'SFC IO/Fast Scan Data/VCF212Z1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF264-1', 'SFC IO/Fast Scan Data/VRF264-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF264', 'SFC IO/Fast Scan Data/VRF264-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF254-1', 'SFC IO/Fast Scan Data/VRF254-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF254', 'SFC IO/Fast Scan Data/VRF254-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF244-1', 'SFC IO/Fast Scan Data/VRF244-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF244', 'SFC IO/Fast Scan Data/VRF244-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF234-1', 'SFC IO/Fast Scan Data/VRF234-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF234', 'SFC IO/Fast Scan Data/VRF234-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF224-1', 'SFC IO/Fast Scan Data/VRF224-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF224', 'SFC IO/Fast Scan Data/VRF224-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF214-1', 'SFC IO/Fast Scan Data/VRF214-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF214', 'SFC IO/Fast Scan Data/VRF214-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF209', 'SFC IO/Fast Scan Data/VRF209','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRF209', 'SFC IO/Fast Scan Data/VRF209','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VMF223', 'SFC IO/Fast Scan Data/VMF223','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VMF223', 'SFC IO/Fast Scan Data/VMF223','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VDF030', 'SFC IO/Fast Scan Data/VDF030','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VDF030', 'SFC IO/Fast Scan Data/VDF030','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF212', 'SFC IO/Fast Scan Data/VCF212','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCF211', 'SFC IO/Fast Scan Data/VCF212','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF006-7', 'SFC IO/Fast Scan Data/VRF006-7','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRF006', 'SFC IO/Fast Scan Data/VRF006-7','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VFF009', 'SFC IO/Fast Scan Data/VFF009','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF009', 'SFC IO/Fast Scan Data/VFF009','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VFF109', 'SFC IO/Fast Scan Data/VFF109','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF109', 'SFC IO/Fast Scan Data/VFF109','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VFF209', 'SFC IO/Fast Scan Data/VFF209','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF209', 'SFC IO/Fast Scan Data/VFF209','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT021', 'SFC IO/Fast Scan Data/VRT021','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRT021', 'SFC IO/Fast Scan Data/VRT021','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF120X-1', 'SFC IO/Fast Scan Data/VCF120X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-H2-MTR-SEL', 'SFC IO/Fast Scan Data/VCF120X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF203S', 'SFC IO/Fast Scan Data/VRF203S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-R2-C3-MTR-SEL', 'SFC IO/Fast Scan Data/VRF203S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF202S-2', 'SFC IO/Fast Scan Data/VRF202S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-R2-C2-MTR-SEL', 'SFC IO/Fast Scan Data/VRF202S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF009S-2', 'SFC IO/Fast Scan Data/VRF009S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-R1-C9-MTR-SEL', 'SFC IO/Fast Scan Data/VRF009S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF003S', 'SFC IO/Fast Scan Data/VRF003S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-R1-C3-MTR-SEL', 'SFC IO/Fast Scan Data/VRF003S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF002S-2', 'SFC IO/Fast Scan Data/VRF002S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-R1-C2-MTR-SEL', 'SFC IO/Fast Scan Data/VRF002S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-H2-MTR-USED', 'SFC IO/Fast Scan Data/CS-H2-MTR-USED','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT011VP', 'SFC IO/Fast Scan Data/VRT011VP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRV011', 'SFC IO/Fast Scan Data/VRT011VP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT172', 'SFC IO/Fast Scan Data/VRT172','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRT172T-CTS', 'SFC IO/Fast Scan Data/VRT172','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT172X', 'SFC IO/Fast Scan Data/VRT172X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRT172', 'SFC IO/Fast Scan Data/VRT172X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRT011-OP', 'SFC IO/Fast Scan Data/CS-VRT011-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT011', 'SFC IO/Fast Scan Data/VRT011','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRT011-CTS', 'SFC IO/Fast Scan Data/VRT011','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRP172', 'SFC IO/Fast Scan Data/VRP172','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRP172-CTS', 'SFC IO/Fast Scan Data/VRP172','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF266', 'SFC IO/Fast Scan Data/VRF266','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF266', 'SFC IO/Fast Scan Data/VRF266','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF256', 'SFC IO/Fast Scan Data/VRF256','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF256', 'SFC IO/Fast Scan Data/VRF256','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF246', 'SFC IO/Fast Scan Data/VRF246','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF246', 'SFC IO/Fast Scan Data/VRF246','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF236', 'SFC IO/Fast Scan Data/VRF236','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF236', 'SFC IO/Fast Scan Data/VRF236','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF226', 'SFC IO/Fast Scan Data/VRF226','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF226', 'SFC IO/Fast Scan Data/VRF226','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF216', 'SFC IO/Fast Scan Data/VRF216','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRF216', 'SFC IO/Fast Scan Data/VRF216','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF006R', 'SFC IO/Fast Scan Data/VRF006R','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC276', 'SFC IO/Fast Scan Data/VRF006R','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF502Z-3', 'SFC IO/Fast Scan Data/VRF502Z-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC232', 'SFC IO/Fast Scan Data/VRF502Z-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF503Z-1', 'SFC IO/Fast Scan Data/VRF503Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC223', 'SFC IO/Fast Scan Data/VRF503Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF202S-1', 'SFC IO/Fast Scan Data/VRF202S-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC212', 'SFC IO/Fast Scan Data/VRF202S-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF006Z', 'SFC IO/Fast Scan Data/VRF006Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC206-CTS', 'SFC IO/Fast Scan Data/VRF006Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT700S-4', 'SFC IO/Fast Scan Data/VRT700S-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC041', 'SFC IO/Fast Scan Data/VRT700S-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT701S-2', 'SFC IO/Fast Scan Data/VRT701S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC021', 'SFC IO/Fast Scan Data/VRT701S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VFF264', 'SFC IO/Fast Scan Data/VFF264','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF264T-CTS', 'SFC IO/Fast Scan Data/VFF264','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF209-OP', 'SFC IO/Fast Scan Data/CS-VFF209-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VFF164', 'SFC IO/Fast Scan Data/VFF164','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF164T-CTS', 'SFC IO/Fast Scan Data/VFF164','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF109-OP', 'SFC IO/Fast Scan Data/CS-VFF109-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VFF064', 'SFC IO/Fast Scan Data/VFF064','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF064T-CTS', 'SFC IO/Fast Scan Data/VFF064','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VFF009-OP', 'SFC IO/Fast Scan Data/CS-VFF009-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF209R-5', 'SFC IO/Fast Scan Data/VRF209R-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC209', 'SFC IO/Fast Scan Data/VRF209R-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF409Z-1', 'SFC IO/Fast Scan Data/VRF409Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC049', 'SFC IO/Fast Scan Data/VRF409Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF402Z-2', 'SFC IO/Fast Scan Data/VRF402Z-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC032', 'SFC IO/Fast Scan Data/VRF402Z-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF029R', 'SFC IO/Fast Scan Data/VRF029R','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC029', 'SFC IO/Fast Scan Data/VRF029R','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF403Z-3', 'SFC IO/Fast Scan Data/VRF403Z-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC023', 'SFC IO/Fast Scan Data/VRF403Z-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF002S-1', 'SFC IO/Fast Scan Data/VRF002S-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC012', 'SFC IO/Fast Scan Data/VRF002S-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VMF223-OP', 'SFC IO/Fast Scan Data/CS-VMF223-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VDF030-OP', 'SFC IO/Fast Scan Data/CS-VDF030-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF120VP-2', 'SFC IO/Fast Scan Data/VCF120VP-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCV130-OP', 'SFC IO/Fast Scan Data/VCF120VP-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF120VP-1', 'SFC IO/Fast Scan Data/VCF120VP-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCV130-CTS', 'SFC IO/Fast Scan Data/VCF120VP-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF251S', 'SFC IO/Fast Scan Data/VCF251S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCC250', 'SFC IO/Fast Scan Data/VCF251S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF262S-1', 'SFC IO/Fast Scan Data/VCF262S-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCC202', 'SFC IO/Fast Scan Data/VCF262S-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF109R-2', 'SFC IO/Fast Scan Data/VCF109R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCC140', 'SFC IO/Fast Scan Data/VCF109R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF120X', 'SFC IO/Fast Scan Data/VCF120X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCC120', 'SFC IO/Fast Scan Data/VCF120X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF109S', 'SFC IO/Fast Scan Data/VCF109S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCC110', 'SFC IO/Fast Scan Data/VCF109S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF003S', 'SFC IO/Fast Scan Data/VCF003S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCC003', 'SFC IO/Fast Scan Data/VCF003S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF000S', 'SFC IO/Fast Scan Data/VCF000S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VCC000', 'SFC IO/Fast Scan Data/VCF000S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VXL204-OP', 'SFC IO/Fast Scan Data/CS-VXL204-OP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VXL204-CTS', 'SFC IO/Fast Scan Data/CS-VXL204-CTS','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VXL204X', 'SFC IO/Fast Scan Data/VXL204X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VXC214', 'SFC IO/Fast Scan Data/VXL204X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT734X', 'SFC IO/Fast Scan Data/VRT734X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC734', 'SFC IO/Fast Scan Data/VRT734X','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT701S-3', 'SFC IO/Fast Scan Data/VRT701S-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC021-PSP', 'SFC IO/Fast Scan Data/VRT701S-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT700Z', 'SFC IO/Fast Scan Data/VRT700Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC441', 'SFC IO/Fast Scan Data/VRT700Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRF106', 'SFC IO/Fast Scan Data/CS-VRF106','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRF206', 'SFC IO/Fast Scan Data/CS-VRF206','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT701S-4', 'SFC IO/Fast Scan Data/VRT701S-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC021-SP', 'SFC IO/Fast Scan Data/VRT701S-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF403Z-4', 'SFC IO/Fast Scan Data/VRF403Z-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC023-SPCL', 'SFC IO/Fast Scan Data/VRF403Z-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF503Z-2', 'SFC IO/Fast Scan Data/VRF503Z-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC223-SPCL', 'SFC IO/Fast Scan Data/VRF503Z-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT700S-5', 'SFC IO/Fast Scan Data/VRT700S-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CS-VRC341', 'SFC IO/Fast Scan Data/VRT700S-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VDF060Z', 'SFC IO/CatOut General/VDF060Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CO-VRC060', 'SFC IO/CatOut General/VDF060Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRS910Z', 'SFC IO/CatOut General/VRS910Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CATOUT-RECIPE-STATUS', 'SFC IO/CatOut General/VRS910Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-OIL-MAX-TIME-TO-CLOSED', 'SFC IO/CatOut General/S88-RX-RCP-OIL-MAX-TIME-TO-CLOSED','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-IRG-MAX-TIME-TO-CLOSED', 'SFC IO/CatOut General/S88-RX-RCP-IRG-MAX-TIME-TO-CLOSED','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RCP-CAST-MAX-TIME-TO-CLOSED', 'SFC IO/CatOut General/S88-RCP-CAST-MAX-TIME-TO-CLOSED','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-H2-FLAG', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-H2-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-NH3-FLAG', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-NH3-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('SERIES-PERMISSIVES', 'SFC IO/Cold Stick Permissives/SERIES-PERMISSIVES','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-SERIES-MIN-C6-TO-R2', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-SERIES-MIN-C6-TO-R2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C9-TO-R2-OK-FLAG', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-C9-TO-R2-OK-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-ENB-FLAG', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-ENB-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-VNB-FLAG', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-VNB-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-NO-C3-MIN-RATE', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-NO-C3-MIN-RATE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C3-TO-R2-OK-FLAG', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-C3-TO-R2-OK-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-OIL-FLAG', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-OIL-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-NO-C9-MIN-RATE', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-NO-C9-MIN-RATE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-ETOH-FLAG', 'SFC IO/Cold Stick Permissives/S88-RX-RCP-ETOH-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-OIL-GRADE-FLAG', 'SFC IO/Rate Change/S88-RC-OIL-GRADE-FLAG','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VDF030R-3', 'SFC IO/Rate Change/VDF030R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('OIL-SP', 'SFC IO/Rate Change/VDF030R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF211R-2', 'SFC IO/Rate Change/VCF211R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('RC-NH3-VAN-RATIO-MODE', 'SFC IO/Rate Change/VCF211R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF120R-2', 'SFC IO/Rate Change/VCF120R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('RC-H2-VAN-RATIO-MODE', 'SFC IO/Rate Change/VCF120R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF209R-2', 'SFC IO/Rate Change/VRF209R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('RC-SEC-C9-C2-RATIO-MODE', 'SFC IO/Rate Change/VRF209R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF409R-2', 'SFC IO/Rate Change/VRF409R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('RC-MAIN-C9-C2-RATIO-MODE', 'SFC IO/Rate Change/VRF409R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF403R-2', 'SFC IO/Rate Change/VRF403R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('RC-MAIN-C3-C2-RATIO-MODE', 'SFC IO/Rate Change/VRF403R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF503R-3', 'SFC IO/Rate Change/VRF503R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('RC-SEC-C3-C2-RATIO-MODE', 'SFC IO/Rate Change/VRF503R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF403Z-1', 'SFC IO/Rate Change/VRF403Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('RC-MAIN-C3-FLOW-MODE', 'SFC IO/Rate Change/VRF403Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF000R-3', 'SFC IO/Rate Change/VCF000R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-VA-TO-C2-RATIO', 'SFC IO/Rate Change/VCF000R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-TOTAL-ENB-SLOPE', 'SFC IO/Rate Change/S88-RC-TOTAL-ENB-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-TOTAL-C3-SLOPE', 'SFC IO/Rate Change/S88-RC-TOTAL-C3-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-TOTAL-C2-SLOPE', 'SFC IO/Rate Change/S88-RC-TOTAL-C2-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CRX_HB-7', 'SFC IO/Rate Change/CRX_HB-7','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-SS6-FLOW', 'SFC IO/Rate Change/CRX_HB-7','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CRX_HB-6', 'SFC IO/Rate Change/CRX_HB-6','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-SS5-FLOW', 'SFC IO/Rate Change/CRX_HB-6','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CRX_HB-5', 'SFC IO/Rate Change/CRX_HB-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-SS4-FLOW', 'SFC IO/Rate Change/CRX_HB-5','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CRX_HB-4', 'SFC IO/Rate Change/CRX_HB-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-SS3-FLOW', 'SFC IO/Rate Change/CRX_HB-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CRX_HB-3', 'SFC IO/Rate Change/CRX_HB-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-SS2-FLOW', 'SFC IO/Rate Change/CRX_HB-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('CRX_HB-2', 'SFC IO/Rate Change/CRX_HB-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-SS1-FLOW', 'SFC IO/Rate Change/CRX_HB-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG530Z', 'SFC IO/Rate Change/VRG530Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-SINGLE-CAT-EFFICIENCY', 'SFC IO/Rate Change/VRG530Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG531Z', 'SFC IO/Rate Change/VRG531Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-SERIES-CAT-EFFICIENCY', 'SFC IO/Rate Change/VRG531Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF209R-3', 'SFC IO/Rate Change/VRF209R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R2-ENB-TO-C2-RATIO', 'SFC IO/Rate Change/VRF209R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRK203-1', 'SFC IO/Rate Change/VRK203-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R2-C3-VALVE-POSITION', 'SFC IO/Rate Change/VRK203-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRK203', 'SFC IO/Rate Change/VRK203','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R2-C3-VALVE-CTS', 'SFC IO/Rate Change/VRK203','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF503R-4', 'SFC IO/Rate Change/VRF503R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R2-C3-TO-C2-RATIO', 'SFC IO/Rate Change/VRF503R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF503Z', 'SFC IO/Rate Change/VRF503Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R2-C3-RATE', 'SFC IO/Rate Change/VRF503Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF502RP-2', 'SFC IO/Rate Change/VRF502RP-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R2-C2-RATE-RAMPER', 'SFC IO/Rate Change/VRF502RP-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF502Z-1', 'SFC IO/Rate Change/VRF502Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R2-C2-RATE', 'SFC IO/Rate Change/VRF502Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF911R2-2', 'SFC IO/Rate Change/VRF911R2-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R1-POLYSPLIT', 'SFC IO/Rate Change/VRF911R2-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R1-ENB-SLOPE', 'SFC IO/Rate Change/S88-RC-R1-ENB-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R1-C3-SLOPE', 'SFC IO/Rate Change/S88-RC-R1-C3-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-R1-C2-SLOPE', 'SFC IO/Rate Change/S88-RC-R1-C2-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-PS-SLOPE', 'SFC IO/Rate Change/S88-RC-PS-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF9101Z', 'SFC IO/Rate Change/VRF9101Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-POLY-RATE', 'SFC IO/Rate Change/VRF9101Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF211R-4', 'SFC IO/Rate Change/VCF211R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-NH3-TO-VA-RATIO', 'SFC IO/Rate Change/VCF211R-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF409R-3', 'SFC IO/Rate Change/VRF409R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-MAIN-ENB-TO-C2-RATIO', 'SFC IO/Rate Change/VRF409R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF006-4', 'SFC IO/Rate Change/VRF006-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-MAIN-C6-RATE', 'SFC IO/Rate Change/VRF006-4','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF403R-3', 'SFC IO/Rate Change/VRF403R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-MAIN-C3-TO-C2-RATIO', 'SFC IO/Rate Change/VRF403R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF403Z-2', 'SFC IO/Rate Change/VRF403Z-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-MAIN-C3-RATE', 'SFC IO/Rate Change/VRF403Z-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF402RP-2', 'SFC IO/Rate Change/VRF402RP-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-MAIN-C2-RATE-RAMPER', 'SFC IO/Rate Change/VRF402RP-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF402Z-1', 'SFC IO/Rate Change/VRF402Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-MAIN-C2-RATE', 'SFC IO/Rate Change/VRF402Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-H2-TO-VA-SLOPE', 'SFC IO/Rate Change/S88-RC-H2-TO-VA-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF120R-3', 'SFC IO/Rate Change/VCF120R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-H2-TO-VA-RATIO', 'SFC IO/Rate Change/VCF120R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG401Z-1', 'SFC IO/Rate Change/VRG401Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-CEMENT-CONCENTRATION', 'SFC IO/Rate Change/VRG401Z-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RC-CAT-EFF-SLOPE', 'SFC IO/Rate Change/S88-RC-CAT-EFF-SLOPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C2-HI-LIM', 'SFC IO/Cold Stick Lab Limits/S88-RX-RCP-C2-HI-LIM','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C2-LO-LIM', 'SFC IO/Cold Stick Lab Limits/S88-RX-RCP-C2-LO-LIM','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF262R-3', 'SFC IO/Cold Stick Lab Limits/VCF262R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-ALKYL-CONC', 'SFC IO/Cold Stick Lab Limits/VCF262R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF109R-1', 'SFC IO/Cold Stick Lab Limits/VCF109R-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-ETOH-CONC', 'SFC IO/Cold Stick Lab Limits/VCF109R-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C9-HI-LIM', 'SFC IO/Cold Stick Lab Limits/S88-RX-RCP-C9-HI-LIM','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VFA009ME', 'SFC IO/Cold Stick Lab Limits/VFA009ME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-CAST-CONC', 'SFC IO/Cold Stick Lab Limits/VFA009ME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF262Z1', 'SFC IO/Cold Stick Lab Limits/VCF262Z1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-ALKYL-AND-SWEEP', 'SFC IO/Cold Stick Lab Limits/VCF262Z1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF211', 'SFC IO/Cold Stick Lab Limits/VCF211','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-NH3-SWEEP', 'SFC IO/Cold Stick Lab Limits/VCF211','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF111', 'SFC IO/Cold Stick Lab Limits/VCF111','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-ETOH-SWEEP', 'SFC IO/Cold Stick Lab Limits/VCF111','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C9-LO-LIM', 'SFC IO/Cold Stick Lab Limits/S88-RX-RCP-C9-LO-LIM','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF221S', 'SFC IO/Cold Stick Lab Limits/VCF221S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-VAN-SWEEP', 'SFC IO/Cold Stick Lab Limits/VCF221S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF012', 'SFC IO/Cold Stick Lab Limits/VCF012','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-VOCL3-SWEEP', 'SFC IO/Cold Stick Lab Limits/VCF012','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-CRX-MIX-TEE-FLOW', 'SFC IO/Cold Stick Lab Limits/S88-RX-RCP-CRX-MIX-TEE-FLOW','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF000R-2', 'SFC IO/Cold Stick Lab Limits/VCF000R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-CAT2D901', 'SFC IO/Cold Stick Lab Limits/VCF000R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG631Z', 'SFC IO/Cold Stick General/VRG631Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C3STRM_C2', 'SFC IO/Cold Stick General/VRG631Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG633Z', 'SFC IO/Cold Stick General/VRG633Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C3STRM_C3', 'SFC IO/Cold Stick General/VRG633Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG637Z', 'SFC IO/Cold Stick General/VRG637Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C3STRM_C3O', 'SFC IO/Cold Stick General/VRG637Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT701S-1', 'SFC IO/Cold Stick General/VRT701S-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-RX-INLET-TEMP-PV', 'SFC IO/Cold Stick General/VRT701S-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT700S-3', 'SFC IO/Cold Stick General/VRT700S-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-OUTLET-TEMP-PV', 'SFC IO/Cold Stick General/VRT700S-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT700S-2', 'SFC IO/Cold Stick General/VRT700S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-OUTLET-TEMP-SP', 'SFC IO/Cold Stick General/VRT700S-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRT701S', 'SFC IO/Cold Stick General/VRT701S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-RX-INLET-TEMP-SP', 'SFC IO/Cold Stick General/VRT701S','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRG632Z', 'SFC IO/Cold Stick General/VRG632Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-C3STRM_C2O', 'SFC IO/Cold Stick General/VRG632Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF262R-2', 'SFC IO/Cold Stick General/VCF262R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-AL-TO-VA', 'SFC IO/Cold Stick General/VCF262R-2','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCF211R-3', 'SFC IO/Cold Stick General/VCF211R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-N-TO-VA', 'SFC IO/Cold Stick General/VCF211R-3','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VCT205X-1', 'SFC IO/Cold Stick General/VCT205X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-CAT-MIXING-TEE-T', 'SFC IO/Cold Stick General/VCT205X-1','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-CRX-DILUTION-C6-T', 'SFC IO/Cold Stick General/S88-RX-RCP-CRX-DILUTION-C6-T','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-CRX-SS-T', 'SFC IO/Cold Stick General/S88-RX-RCP-CRX-SS-T','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('RX-RECIPE', 'SFC IO/Cold Stick Recipe/RX-RECIPE','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-E202-BYPASS-DELTA-TIME', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-E202-BYPASS-DELTA-TIME','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-E202-BYPASS-POSITION', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-E202-BYPASS-POSITION','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-E204-LEVEL', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-E204-LEVEL','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-E204-TEMP', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-E204-TEMP','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-GEL-DELAY', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-GEL-DELAY','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-CA-TARGET', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-CA-TARGET','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF264Z', 'SFC IO/Cold Stick Recipe/VRF264Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-SS6-NOZZLE', 'SFC IO/Cold Stick Recipe/VRF264Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF254Z', 'SFC IO/Cold Stick Recipe/VRF254Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-SS5-NOZZLE', 'SFC IO/Cold Stick Recipe/VRF254Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF244Z', 'SFC IO/Cold Stick Recipe/VRF244Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-SS4-NOZZLE', 'SFC IO/Cold Stick Recipe/VRF244Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF234Z', 'SFC IO/Cold Stick Recipe/VRF234Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-SS3-NOZZLE', 'SFC IO/Cold Stick Recipe/VRF234Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF224Z', 'SFC IO/Cold Stick Recipe/VRF224Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-SS2-NOZZLE', 'SFC IO/Cold Stick Recipe/VRF224Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('VRF214Z', 'SFC IO/Cold Stick Recipe/VRF214Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-SS1-NOZZLE', 'SFC IO/Cold Stick Recipe/VRF214Z','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-CA-EFFICIENCY', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-CA-EFFICIENCY','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-TOTAL-HEAT-OF-RX', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-TOTAL-HEAT-OF-RX','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-R1-HEAT-OF-RX', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-R1-HEAT-OF-RX','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-MW-ALKYL', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-MW-ALKYL','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('S88-RX-RCP-MW-VAN', 'SFC IO/Cold Stick Recipe/S88-RX-RCP-MW-VAN','DOUBLE');
insert into TagMap (GSIName, TagPath, DataType) values ('', 'SFC IO//','DOUBLE');
