-- Fields aare:  G2 class name, Ignition factory-id, type (enclosure/transition/ )
minsert into SfcClassMap values ('S88-BEGIN','begin-step','');
minsert into SfcClassMap values ('S88-TIME-DELAY','com.ils.timedDelayStep','');
minsert into SfcClassMap values ('S88-ABORT-BLOCK', 'com.ils.abortStep','');
minsert into SfcClassMap values ('S88-ABORT-TASK', 'com.ils.abortStep','');
minsert into SfcClassMap values ('S88-CALLBACK','action-step','');
minsert into SfcClassMap values ('S88-CLEAR-QUEUE-TASK','com.ils.clearQueueStep','');
minsert into SfcClassMap values ('S88-COLLECT-DATA-TASK','com.ils.collectDataStep','');
minsert into SfcClassMap values ('S88-CONFIRM-CONTROLLER-MODES','com.ils.confirmControllerModesStep','');
minsert into SfcClassMap values ('S88-DATABASE-SIMPLE-QUERY-TASK','com.ils.simpleQueryStep','');
minsert into SfcClassMap values ('S88-MESSAGE-CONSOLE-TASK','com.ils.controlPanelMessageStep','');
minsert into SfcClassMap values ('S88-REMOVE-BUSY-NOTIFICATION-TASK','com.ils.deleteDelayNotification','');
minsert into SfcClassMap values ('S88-SHOW-NOTIFICATION-DIALOG-TASK','com.ils.dialogMessageStep','');
minsert into SfcClassMap values ('S88-ENABLE-OR-DISABLE-COMMAND-TASK','com.ils.enableDisableStep','');
minsert into SfcClassMap values ('S88-ENCAPSULATION-TASK', 'enclosing-step','enclosure');
minsert into SfcClassMap values ('S88-END', 'end-step','');
minsert into SfcClassMap values ('S88-GET-INPUT-TASK','com.ils.inputStep','');
minsert into SfcClassMap values ('S88-HOLD-TASK','com.ils.pauseStep','');
minsert into SfcClassMap values ('S88-LIBRARY-TASK','enclosing-step','');
minsert into SfcClassMap values ('S88-LIBRARY-CALLER','enclosing-step','');
minsert into SfcClassMap values ('S88-MANUAL-DATA-ENTRY-TASK','com.ils.dataEntryStep','');
minsert into SfcClassMap values ('S88-MONITOR-DOWNLOADS-TASK','com.ils.monitorDownloadsStep','');
minsert into SfcClassMap values ('S88-PV-MONITORING-TASK','com.ils.pvMonitoringStep','');
minsert into SfcClassMap values ('S88-MESSAGE_QUEUE-TASK','com.ils.queueMessageStep','');
minsert into SfcClassMap values ('S88-PAUSE-TASK','com.ils.pauseStep','');
minsert into SfcClassMap values ('S88-POST-BUSY-NOTIFICATION-TASK','com.ils.postDelayNotification','');
minsert into SfcClassMap values ('S88-PRINT-OR-VIEW-FILE-TASK','com.ils.printFileStep','');
minsert into SfcClassMap values ('S88-PRINT-WORKSPACE-TASK','com.ils.printWindowStep','');
minsert into SfcClassMap values ('S88-DATABASE-RAW-QUERY-TASK','com.ils.rawQueryStep','');
minsert into SfcClassMap values ('S88-REVIEW-DATA-TASK','com.ils.reviewDataStep','');
minsert into SfcClassMap values ('S88-REVIEW-DATA-WITH-ADVICE-TASK', 'com.ils.reviewDataWithAdviceStep','');
minsert into SfcClassMap values ('S88-REVIEW-FLOWS-TASK','com.ils.reviewFlowsStep','');
minsert into SfcClassMap values ('S88-SAVE-RECIPE-DATA-TO-CSV','com.ils.saveDataStep','');
minsert into SfcClassMap values ('S88-SELECT-INPUT-TASK','com.ils.selectInputStep','');
minsert into SfcClassMap values ('S88-SET-QUEUE-TASK','com.ils.setQueueStep','');
minsert into SfcClassMap values ('S88-SHOW-QUEUE-TASK','com.ils.showQueueStep','');
minsert into SfcClassMap values ('S88-STOP-BLOCK','com.ils.abortStep','');
minsert into SfcClassMap values ('S88-STOP-TASK','com.ils.abortStep','');
minsert into SfcClassMap values ('S88-TIMEOUT-BLOCK','com.ils.timedDelayStep','');
minsert into SfcClassMap values ('S88-WRITE-FILE-TASK','com.ils.writeFileStep','');
minsert into SfcClassMap values ('S88-WRITE-OUTPUTS-TASK','com.ils.writeOutputsStep','');
minsert into SfcClassMap values ('S88-YES-NO-TASK','com.ils.yesNoStep','');
minsert into SfcClassMap values ('S88-UNIT-PROCEDURE','com.ils.procedureStep','enclosure');
m-- insert into SfcClassMap values ('S88-UNIT-PROCEDURE','enclosing-step','enclosure');
minsert into SfcClassMap values ('S88-OPERATION','com.ils.operationStep','enclosure');
minsert into SfcClassMap values ('S88-PHASE','com.ils.phaseStep','enclosure');
minsert into SfcClassMap values ('S88-CONDITIONAL-TRANSITION','transition','transition');
minsert into SfcClassMap values ('S88-PARALLEL-TRANSITION','parallel','parallel');
