-- Map G2 GSI names to Ignition Tags
-- Columns are GSI name, tag path
-- NOTE: value is not a legitimate tag name
-- NOTE: Tag names must be unique, folder placement is immaterial.
insert into TagMap values ('A-BALER-TEMP-LAB-DATA','[]LabData/A_BALER_TEMP/value','DOUBLE');
insert into TagMap values ('AB-BALER-TEMP-LAB-DATA','[]LabData/AB_BALER_TEMP/value','DOUBLE');
insert into TagMap values ('AB-BALER-VOL-LAB-DATA','[]LabData/AB_BALER_VOL_LAB_DATA/value','DOUBLE');
insert into TagMap values ('AB-BALER-VOL-FTNIR-DATA','[]LabData/AB_BALER_VOL_FTNIR/value','DOUBLE');
insert into TagMap values ('ALKYL_FLOW','[]LabData/ALKYL_FLOW/value','DOUBLE');
insert into TagMap values ('B-BALER-TEMP-LAB-DATA','[]LabData/B_BALER_TEMP/value','DOUBLE');
insert into TagMap values ('C-BALER-TEMP-LAB-DATA','[]LabData/C_BALER_TEMP/value','DOUBLE');
insert into TagMap values ('C_FLYING_SWITCH-GDA-INPUT','[]Tags/C_FLYING_SWITCH','DOUBLE');
insert into TagMap values ('CA-LAB-DATA','[]LabData/CA','DOUBLE');
insert into TagMap values ('C2-LAB-DATA','[]LabData/C2/value','DOUBLE');
insert into TagMap values ('C2-LAB-DATA-FOR-R1-NLC','[]LabData/C2_R1_NLC','DOUBLE');
insert into TagMap values ('C2_FLOW','[]LabData/C2_FLOW/value','DOUBLE');
insert into TagMap values ('C3_CONVERSION','[]Tags/C3_CONVERSION/value','DOUBLE');
insert into TagMap values ('C3CONV_LOW_LIMIT','[]Tags/C3_CONVERSION/lowLimit','DOUBLE');
insert into TagMap values ('C3-PURITY-HI','[]Tags/C3_PURITY_HI','DOUBLE');
insert into TagMap values ('C6_RX_FEED-VNB','[]Tags/C6_RX_IN_FEED','DOUBLE');
insert into TagMap values ('C9-IN-CRUMB','[]Tags/C9_IN_CRUMB','DOUBLE');
insert into TagMap values ('C9-GRADE-FLAG','[]Tags/C9_GRADE_FLAG/value','DOUBLE');
insert into TagMap values ('C9-LAB-DATA','[]LabData/C9_LAB_DATA/value','DOUBLE');
insert into TagMap values ('C9-SPEC-LIMIT-IN-FEED','[]LabData/C9_SPEC_LIMIT_IN_FEED','DOUBLE');
insert into TagMap values ('C101-ETHYLENE','[]Tags/C101_ETHYLENE','DOUBLE');
insert into TagMap values ('CAT_EFFICIENCY','[]Tags/CAT_EFFICIENCY/value','DOUBLE');
insert into TagMap values ('CATEFF_HIGH_LIMIT','[]Tags/CAT_EFFICIENCY/highLimit','DOUBLE');
insert into TagMap values ('CAT_EFF_HIGH_LIMIT','[]Tags/CAT_EFFICIENCY/highLimit','DOUBLE');
insert into TagMap values ('CAT_PREMIX_TEMP','[]Tags/CAT_PREMIX_TEMP/value','DOUBLE');
insert into TagMap values ('CD-BALER-TEMP-LAB-DATA','[]Tags/CD_BALER_TEMP_LAB_DATA/value','DOUBLE');
insert into TagMap values ('CD-BALER-VOL-LAB-DATA','[]Tags/CD_BALER_VOL','DOUBLE');
insert into TagMap values ('CD-BALER-VOL-ftnir-DATA','[]Tags/CD_BALER_VOL_FTNIR_DATA','DOUBLE');
insert into TagMap values ('CD-BALER-VOL-FTNIR-DATA','[]Tags/CD_BALER_VOL_FTNIR_DATA','DOUBLE');
insert into TagMap values ('CNTR_AVG_TPR_TIP_HT','[]Tags/CNTR_AVG_TPR_TIP_HT/value','DOUBLE');
insert into TagMap values ('CNTR_AVG_TPR_TIP_HT_MAX_DEADBAND','[]Tags/CNTR_AVG_TPR_TIP_HT/maxDeadband','DOUBLE');
insert into TagMap values ('CNTR_AVG_TPR_TIP_HT_TARGET','[]Tags/CNTR_AVG_TPR_TIP_HT/target','DOUBLE');
insert into TagMap values ('CRX-BLOCK-POLYMER-FLAG','[]Tags/CRX_BLOCK_POLYMER_FLAG/value','DOUBLE');
insert into TagMap values ('CRX_HB-3','[]Tags/CRX_HB_3','DOUBLE');
insert into TagMap values ('D-BALER-TEMP-LAB-DATA','[]LabData/D_BALER_TEMP_LAB_DATA/value','DOUBLE');
insert into TagMap values ('DC2-LAB-DATA','[]LabData/DC2_LAB_DATA/value','DOUBLE');
insert into TagMap values ('DC9-LAB-DATA','[]LabData/DC9_LAB_DATA/value','DOUBLE');
insert into TagMap values ('DML-LAB-DATA','[]LabData/DML_LAB_DATA/value','DOUBLE');
insert into TagMap values ('DML-SQC-FLAG','[]LabData/DML_SQC_FLAG','DOUBLE');
insert into TagMap values ('E-BALER-TEMP-LAB-DATA','[]LabData/E_BALER_TEMP/value','DOUBLE');
insert into TagMap values ('E-BALER-VOL-LAB-DATA','[]LabData/E_BALER_VOL/value','DOUBLE');
insert into TagMap values ('E-BALER-VOL-FTNIR-DATA','[]LabData/E_BALER_VOL_FTNIR/value','DOUBLE');
insert into TagMap values ('FRNT_AVG_C2','[]Tags/FRNT_AVG_C2/value','DOUBLE');
insert into TagMap values ('FRNT_AVG_C2_HIGH_LIMIT','[]Tags/FRNT_AVG_C2/highLimit','DOUBLE');
insert into TagMap values ('FRNT_FEED_DIFF','[]Tags/FRNT_FEED_DIFF/value','DOUBLE');
insert into TagMap values ('FRNT_LNGTH','[]Tags/FRNT_LNGTH/value','DOUBLE');
insert into TagMap values ('FRNT_LNGTH_HIGH_LIMIT','[]Tags/FRNT_LNGTH/highLimit','DOUBLE');
insert into TagMap values ('FRNT_LNGTH_LOW_LIMIT','[]Tags/FRNT_LNGTH/lowLimit','DOUBLE');
insert into TagMap values ('FRNT_LNGTH_TARGET','[]Tags/FRNT_LNGTH/target','DOUBLE');
insert into TagMap values ('FRNT_SDSTRM_MAX_DIFF','[]Tags/FRNT_SDSTRM/maxDiff','DOUBLE');
insert into TagMap values ('FRNT_TPR_TIP_HT_HIGH_LIMIT','[]Tags/FRNT_TPR_TIP_HT/highLimit','DOUBLE');
insert into TagMap values ('FRNT_TPR_TIP_HT_DIFF','[]Tags/FRNT_TPR_TIP_HT/diff','DOUBLE');
insert into TagMap values ('FRNT_TPR_TIP_HT_MAX_DIFF','[]Tags/FRNT_TPR_TIP_HT/maxDiff','DOUBLE');
insert into TagMap values ('MAX_CNTR_TPR_TIP_DELTA_FM_AVG','[]Tags/MAX_CNTR_TPR_TIP_DELTA_FM_AVG/value','DOUBLE');
insert into TagMap values ('MIXTEE_IN_USE_0_EAST_1_WEST','[]Tags/MIXTEE_IN_USE_0_EAST_1_WEST/value','DOUBLE');
insert into TagMap values ('MLR-GRADE-FLAG','[]Tags/MLR_GRADE_FLAG','DOUBLE');
insert into TagMap values ('MLR-LAB-DATA','[]LabData/MLR_LAB_DATA/value','DOUBLE');
insert into TagMap values ('MOONEY-LAB-DATA','[]LabData/MOONEY/value','DOUBLE');
insert into TagMap values ('MOONEY_RESET_TIME_FOR_SF-3','[]Tags/MOONEY_RESET_TIME_FOR_SF_3/value','DOUBLE');
insert into TagMap values ('OIL-GRADE-FLAG','[]Tags/OIL_GRADE_FLAG/value','DOUBLE');
insert into TagMap values ('OIL-LAB-DATA','[]LabData/OIL_LAB_DATA/value','DOUBLE');
insert into TagMap values ('POLYSPLIT-DATA','[]LabData/POLYSPLIT_DATA/highLImit','DOUBLE');
insert into TagMap values ('POLYSPLIT-SQC-FLAG','[]Tags/POLYSPLIT_SQC_FLAG/highLImit','DOUBLE');
insert into TagMap values ('POLY_RATE_CHANGE-GDA-INPUT','[]Tags/POLY_RATE_CHANGE/gdaInput','DOUBLE');
insert into TagMap values ('PREMIX_LINE_DATA_OK-GDA','[]Tags/PREMIX_LINE_DATA_OK','BOOLEAN');
insert into TagMap values ('PREMIX_LINE_FRESH-GDA-PARAMETER','[]Tags/PREMIX_LINE_FRESH_PARAMETER','DOUBLE');
insert into TagMap values ('PREMIX_TEMP_HIGH_LIMIT','[]Tags/PREMIX_TEMP/highLImit','DOUBLE');
insert into TagMap values ('PROD-CA-SQC-FLAG','[]Tags/PROD_CA_SQC_FLAG/highLImit','DOUBLE');
insert into TagMap values ('PROD-ML-LAB-DATA','[]LabData/PROD_ML_LAB_DATA/highLImit','DOUBLE');
insert into TagMap values ('PROD-ML-VFU-OK','[]Tags/PROD_ML_VFU_OK','DOUBLE');
insert into TagMap values ('RLA3-CURRENT-GRADE','[]Tags/RLA3-CURRENT-GRADE','DOUBLE');
insert into TagMap values ('RX_CONFIGURATION','[]Tags/RX_CONFIGURATION/value','DOUBLE');
insert into TagMap values ('SD-STRM-C2_FLOW','[]Tags/SD_STRM_C2_FLOW','DOUBLE');
insert into TagMap values ('SDSTRM-C3C2-RATIO','[]Tags/SDSTRM_C3C2_RATIO/value','DOUBLE');
insert into TagMap values ('SDSTRM_C3-TO-C2_RATIO_HIGH_LIMIT','[]Tags/SDSTRM_C3-TO-C2_RATIO/highLimit','DOUBLE');
insert into TagMap values ('SDSTRM_C3-TO-C2_RATIO_LOW_LIMIT','[]Tags/SDSTRM_C3-TO-C2_RATIO/lowLimit','DOUBLE');
insert into TagMap values ('SPLIT_RATE_CHANGE-GDA-INPUT','[]Tags/SPLIT_RATE_CHANGE/value','DOUBLE');
insert into TagMap values ('SS1_TAPER_TIP_HEIGHT','[]Tags/SS1_TAPER_TIP_HEIGHT/value','DOUBLE');
insert into TagMap values ('STAB-LAB-DATA','[]LabData/STAB_LAB_DATA/value','DOUBLE');
insert into TagMap values ('VFU-BALER-TEMP-CHK','[]Tags/VFU_BALER_TEMP_CHK','DOUBLE');
insert into TagMap values ('SS2_TAPER_TIP_HEIGHT','[]Tags/SS2_TAPER_TIP_HEIGHT/value','DOUBLE');
insert into TagMap values ('VFU-FTNIR-GRADE','[]Tags/VFU_FTNIR_GRADE','DOUBLE');
-- UDT paths
insert into TagMap values ('[the target of A-BALER-TEMP-LAB-DATA]','[]LabData/A_BALER_TEMP/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of A-BALER-TEMP-LAB-DATA]','[]LabData/A_BALER_TEMP/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of AB-BALER-TEMP-LAB-DATA]','[]LabData/AB_BALER_TEMP/target','DOUBLE');
insert into TagMap values ('[the target of AB-BALER-VOL-ftnir-DATA]','[]LabData/AB_BALER_VOL_FTNIR/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of AB-BALER-VOL-ftnir-DATA]','[]LabData/AB_BALER_VOL_FTNIR/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of AB-BALER-VOL-lab-DATA]','[]LabData/AB_BALER_VOL_lab/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of AB-BALER-VOL-lab-DATA]','[]LabData/AB_BALER_VOL_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the target of B-BALER-TEMP-LAB-DATA]','[]LabData/B_BALER_TEMP/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of B-BALER-TEMP-LAB-DATA]','[]LabData/B_BALER_TEMP_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of C-BALER-TEMP-LAB-DATA]','[]LabData/C_BALER_TEMP_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of C-BALER-TEMP-LAB-DATA]','[]LabData/C_BALER_TEMP_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of C2-LAB-DATA]','[]LabData/C2/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of C2-LAB-DATA]','[]LabData/C2/target','DOUBLE');
insert into TagMap values ('[the bad-value of C3_CONVERSION]','[]Tags/C3_CONVERSION/badValue','STRING');
insert into TagMap values ('[the bad-value of C9-GRADE-FLAG]','[]Tags/C9_GRADE_FLAG/badValue','STRING');
insert into TagMap values ('[the bad-value of RX_CONFIGURATION]','[]Tags/RX_CONFIGURATION/badValue','STRING');
insert into TagMap values ('[the standard-deviation of c9-lab-data]','[]LabData/C9_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of c9-lab-data]','[]LabData/C9_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of CA-LAB-DATA]','[]LabData/CA_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of CA-LAB-DATA]','[]LabData/CA_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the bad-value of CAT_EFFICIENCY]','[]Tags/CAT_EFFICIENCY/badValue','STRING');
insert into TagMap values ('[the bad-value of CAT_PREMIX_TEMP]','[]Tags/CAT_PREMIX_TEMP/badValue','STRING');
insert into TagMap values ('[the standard-deviation of CD-BALER-VOL-ftnir-DATA]','[]LabData/CD_BALER_VOL_ftnir_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of CD-BALER-VOL-ftnir-DATA]','[]LabData/CD_BALER_VOL_ftnir_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of CD-BALER-VOL—lab-DATA]','[]LabData/CD_BALER_VOL_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of CD-BALER-VOL-lab-DATA]','[]LabData/CD_BALER_VOL_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of CD-BALER-VOL-lab-DATA]','[]LabData/CD_BALER_VOL_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of CD-BALER-VOL—lab-DATA]','[]LabData/CD_BALER_VOL_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the bad-value of CNTR_AVG_TPR_TIP_HT]','[]Tags/CNTR_AVG_TPR_TIP_HT/badValue','STRING');
insert into TagMap values ('[the bad-value of CRX-BLOCK-POLYMER-FLAG]','[]Tags/CRX_BLOCK_POLYMER_FLAG/badValue','STRING');
insert into TagMap values ('[the standard-deviation of D-BALER-TEMP-LAB-DATA]','[]LabData/D_BALER_TEMP_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of D-BALER-TEMP-LAB-DATA]','[]LabData/D_BALER_TEMP_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of DC2-LAB-DATA]','[]LabData/DC2_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of DC2-LAB-DATA]','[]LabData/DC2_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of Dc9-lab-data]','[]LabData/DC9_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of Dc9-lab-data]','[]LabData/DC9_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of DML-LAB-DATA]','[]LabData/DML_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of DML-LAB-DATA]','[]LabData/DML_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of E-BALER-TEMP-LAB-DATA]','[]LabData/E_BALER_TEMP_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of E-BALER-TEMP-LAB-DATA]','[]LabData/E_BALER_TEMP_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of E-BALER-VOL-lab-DATA]','[]LabData/E_BALER_VOL_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of E-BALER-VOL-ftnir-DATA]','[]LabData/E_BALER_VOL_FTNIR/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of E-BALER-VOL-lab-DATA]','[]LabData/E_BALER_VOL/target','DOUBLE');
insert into TagMap values ('[the target of E-BALER-VOL-ftnir-DATA]','[]Tags/E_BALER_VOL_FTNIR/target','DOUBLE');
insert into TagMap values ('[the bad-value of FRNT_AVG_C2]','[]Tags/FRNT_AVG_C2/badValue','STRING');
insert into TagMap values ('[the bad-value of FRNT_FEED_DIFF]','[]Tags/FRNT_FEED_DIFF/badValue','STRING');
insert into TagMap values ('[the time-of-most-recent-recommendation-implementation of frnt_short_use_temp-gda]','[]Tags/FRNT_SHORT_USE_TEMP_GDA/implementationTime','INTEGER');
insert into TagMap values ('[the bad-value of FRNT_TPR_TIP_HT_DIFF]','[]Tags/FRNT_TPR_TIP_HT_DIFF/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of MAX_CNTR_TPR_TIP_DELTA_FM_AVG]','[]Tags/MAX_CNTR_TPR_TIP_DELTA_FM_AVG/badValue','DOUBLE');
insert into TagMap values ('[the standard-deviation of MLR-LAB-DATA]','[]LabData/MLR_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of MLR-LAB-DATA]','[]LabData/MLR_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the bad-value of MIXTEE_IN_USE_0_EAST_1_WEST]','[]Tags/MIXTEE_IN_USE_0_EAST_1_WEST/badValue','DOUBLE');
insert into TagMap values ('[the standard-deviation of MOONEY-LAB-DATA]','[]LabData/MOONEY/standardDeviation','DOUBLE');
insert into TagMap values ('[the unix-sample-time of mooney-lab-data]','[]LabData/MOONEY/sampleTime','INTEGER');
insert into TagMap values ('[the target of MOONEY-LAB-DATA]','[]LabData/MOONEY/target','DOUBLE');
insert into TagMap values ('[the bad-value of MOONEY_RESET_TIME_FOR_SF-3]','[]Tags/MOONEY_RESET_TIME_FOR_SF_3/badValue','DOUBLE');
insert into TagMap values ('[the time-of-most-recent-grade-change of rla3-run-hours]','[]Tags/RLA3_RUN_HOURS/gradeChangeTime','INTEGER');
insert into TagMap values ('[the standard-deviation of OIL-LAB-DATA]','[]LabData/OIL_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of OIL-LAB-DATA]','[]LabData/OIL_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of POLYSPLIT-DATA]','[]LabData/POLYSPLIT_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of POLYSPLIT-DATA]','[]LabData/POLYSPLIT_DATA/target','DOUBLE');
insert into TagMap values ('[the standard-deviation of PROD-ML-LAB-DATA]','[]LabData/PROD_ML_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of PROD-ML-LAB-DATA]','[]LabData/PROD_ML_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the bad-value of ALKYL_FLOW]','[]LabData/ALKYL_FLOW/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of C2_FLOW]','[]LabData/C2_FLOW/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of FRNT_LNGTH]','[]Tags/FrontLength/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of OIL-GRADE-FLAG]','[]Tags/OIL_GRADE_FLAG/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of RLA3-CURRENT-GRADE]','[]Tags/RLA3_CURRENT_GRADE/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of RX_CONFIGURATION]','[]Tags/RX_CONFIGURATION/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of RX_CONFIGURATION ]','[]Tags/RX_CONFIGURATION/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of SDSTRM-C3C2-RATIO]','[]Tags/SDSTRM_C3C2_RATIO/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of SD-STRM-C2_FLOW]','[]Tags/SDSTRM_C2_FLOW/badValue','DOUBLE');
insert into TagMap values ('[the bad-value of SS1_TAPER_TIP_HEIGHT]','[]Tags/SS1_TAPER_TIP_HEIGHT/badValue','DOUBLE');
insert into TagMap values ('[the standard-deviation of STAB-LAB-DATA]','[]LabData/STAB_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of STAB-LAB-DATA]','[]LabData/STAB_LAB_DATA/target','DOUBLE');
insert into TagMap values ('[the bad-value of SS2_TAPER_TIP_HEIGHT]','[]Tags/SS2_TAPER_TIP_HEIGHT/badValue','DOUBLE');
-- The following entries map the names of G2 parameter and variable objects into Ignition Tags
insert into TagMap values ('CATIN-GDA-COUNTER','[]Parameters/CatinCounter','STRING');
insert into TagMap values ('CATIN-GDA-PROD-ML-ACTIVE','[]Parameters/CatinProdMlActive','STRING');
insert into TagMap values ('EM-GDA-LOGICAL-VARIABLE-XXX-2','[]Parameters/LogicalVariable2','STRING');
insert into TagMap values ('EM-GDA-LOGICAL-VARIABLE-XXX-293','[]Parameters/LogicalVariable293','STRING');
insert into TagMap values ('EM-GDA-SYMBOLIC-VARIABLE-XXX-291','[]Parameters/SymbolicVariable291','STRING');
insert into TagMap values ('EM-GDA-SYMBOLIC-VARIABLE-XXX-292','[]Parameters/SymbolicVariable292','STRING');
insert into TagMap values ('EM-GDA-SYMBOLIC-VARIABLE-XXX-429','[]Parameters/SymbolicVariable429','STRING');
insert into TagMap values ('EM-GDA-SYMBOLIC-VARIABLE-XXX-4651','[]Parameters/SymbolicVariable4651','STRING');
insert into TagMap values ('FREEZER-SAMPLE-SWITCH','[]Parameters/FreezerSampleSwitch','STRING');
insert into TagMap values ('SERIES_FLYING_SWITCH-GDA-INPUT','[]Parameters/SeriesFlyingSwitchInput','STRING');
insert into TagMap values ('SINGLE_FLYING_SWITCH-GDA-INPUT','[]Parameters/SingleFlyingSwitchInput','STRING');
insert into TagMap values ('SERIES_RATE_CHANGE-GDA-INPUT','[]Parameters/SeriesRateChangeInput','STRING');
insert into TagMap values ('SINGLE_RATE_CHANGE-GDA-INPUT','[]Parameters/SingleRateChangeInput','STRING');
insert into TagMap values ('SPLIT_FLYING_SWITCH-GDA-INPUT','[]Parameters/SplitFlyingSwitchInput','STRING');
-- The foillowing tags represent Source/Sink connections
insert into TagMap values ('AB-BALER-VOL-LAB-SQC-PATH','[]Connections/ABBalerVolLab','STRING');
insert into TagMap values ('AB-BALER-VOL-FTNIR-SQC-PATH','[]Connections/ABBalerVolFtnir','STRING');
insert into TagMap values ('C-D-E-BALER-TEMP-SQC','[]Connections/CDEBalerTemp','STRING');
insert into TagMap values ('C-RX_GRD_PATH-GDA','[]Connections/CRxGrd','STRING');
insert into TagMap values ('C_FLYING_SWITCH_OUTPUT','[]Connections/CFlyingSwitchOutput','STRING');
insert into TagMap values ('C2_SQC_TO_C2_CSTR-GDA','[]Connections/C2SqcToC2Cstr','STRING');
insert into TagMap values ('CA-SQC-TO-CRX-GDA','[]Connections/CaSqcToCrx','STRING');
insert into TagMap values ('CAT_IS_IN','[]Connections/CatIsIna','STRING');
insert into TagMap values ('CAT_IS_IN_PATH-GDA','[]Connections/CatIsInb','STRING');
insert into TagMap values ('CAT_IS_OUT_PATH-GDA','[]Connections/CatIsOut','STRING');
insert into TagMap values ('CD-BALER-VOL-LAB-SQC-PATH','[]Connections/CDBalerVolLab','STRING');
insert into TagMap values ('CD-BALER-VOL-FTNIR-SQC-PATH','[]Connections/CDBalerVolFtnir','STRING');
insert into TagMap values ('E-BALER-VOL-LAB-SQC-PATH','[]Connections/EBalerVolLab','STRING');
insert into TagMap values ('E-BALER-VOL-FTNIR-SQC-PATH','[]Connections/EBalerVolFtnir','STRING');
insert into TagMap values ('FRNT_AVG_C2_NOT_HIGH_PATH-GDA','[]Connections/FrntAvgC2NotHigh','STRING');
insert into TagMap values ('FRNT_LNGTH_ABOVE_SP_PATH-GDA','[]Connections/FrntLngthAboveSP','STRING');
insert into TagMap values ('FRNT_LNGTH_BELOW_SETPOINT_TO_SF-4-GDA','[]Connections/FrntLngthBelowSetpointSF4','STRING');
insert into TagMap values ('FRNT_LNGTH_SHORT_TO_MOONEY_LOGIC-GDA','[]Connections/FrntLngthShortToMooneyLogic','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-490','[]Connections/ConnectionPost490','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-491','[]Connections/ConnectionPost491','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-492','[]Connections/ConnectionPost492','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-568','[]Connections/ConnectionPost568a','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-569','[]Connections/ConnectionPost569','STRING');
insert into TagMap values ('GDL-INFERENCE-PATH-CONNECTION-POST-XXX-488','[]Connections/ConnectionPost488','STRING');
insert into TagMap values ('GDL-INFERENCE-PATH-CONNECTION-POST-XXX-489','[]Connections/ConnectionPost489','STRING');
insert into TagMap values ('GDL-INFERENCE-PATH-CONNECTION-POST-XXX-568','[]Connections/ConnectionPost568b','STRING');
insert into TagMap values ('ML_HIGH-GDA','[]Connections/MlHigh','STRING');
insert into TagMap values ('ML_LOW_PATH-GDA','[]Connections/MlLow','STRING');
insert into TagMap values ('MOONEY_SQC_TO_CSTR_MOONEY-GDA','[]Connections/MooneySqcToCstrMooney','STRING');
insert into TagMap values ('MY-CONNECTION-POST','[]Connections/MyConnectionPost','STRING');
insert into TagMap values ('PREMIX_LINE_FRESH-PATH-GDA','[]Connections/PremixLineFresh','STRING');
insert into TagMap values ('PREMIX_TEMP_AVAIL_PATH-GDA','[]Connections/PremixTempAvail','STRING');
insert into TagMap values ('PREMIX_TEMP_CHG_PERMITTED-PATH-GDA','[]Connections/PremixTempChgPermitted','STRING');
insert into TagMap values ('PREMIX_TEMP_LESS_THAN_MAX_PATH-GDA','[]Connections/PremixTempLessThanMax','STRING');
insert into TagMap values ('POLY_RATE_CHANGE_OUTPUT','[]Connections/PolyRateChangeOutput','STRING');
insert into TagMap values ('RATE_CHANGE_OUTPUT','[]Connections/RateChangeOutput','STRING');
insert into TagMap values ('RX-ML-OK-PATH-GDA','[]Connections/RxMlOk','STRING');
insert into TagMap values ('SDSTRM_C3C2_RATIO','[]Connections/SdstrmC3C2Ratio','STRING');
insert into TagMap values ('SERIES_FLYING_SWITCH_OUTPUT','[]Connections/SeriesFlyingSwitchOutput','STRING');
insert into TagMap values ('SERIES_RATE_CHANGE_OUTPUT','[]Connections/SeriesRateChangeOutput','STRING');
insert into TagMap values ('SINGLE_RATE_CHANGE_OUTPUT','[]Connections/SingleRateChangeOutput','STRING');
insert into TagMap values ('SINGLE_FLYING_SWITCH_OUTPUT','[]Connections/SingleFlyingSwitchOutput','STRING');
insert into TagMap values ('SPLIT_FLYING_SWITCH_OUTPUT','[]Connections/SplitFlyingSwitchOutput','STRING');
insert into TagMap values ('SPLIT_RATE_CHANGE_OUTPUT','[]Connections/SplitRateChangeOutput','STRING');
insert into TagMap values ('STAB_SQC_TO_CRX-GDA','[]Connections/StabSqcToCrx','STRING');
insert into TagMap values ('UNIFORM_CNTR_TPR_TIPS_PATH-GDA','[]Connections/UniformCntrTprTips','STRING');
-- From use cases
insert into TagMap values ('dr-d128a-act','[]Parameters/DR-128a-ACT','DOUBLE');
insert into TagMap values ('dr-d128b-act','[]Parameters/DR-128b-ACT','DOUBLE');
insert into TagMap values ('dr-d128c-act','[]Parameters/DR-128c-ACT','DOUBLE');
insert into TagMap values ('dr-cool-down-start-time','[]Parameters/DR-COOLDOWN-START','STRING');
insert into TagMap values ('s88-test-logical-parameter','[]Parameters/s88TestLogicalParameter','BOOLEAN');
insert into TagMap values ('test-8-path-1','[]Parameters/test8Path1','BOOLEAN');
insert into TagMap values ('test-8-path-2','[]Parameters/test8Path2','BOOLEAN');
