-- NOTE: Tag names must be unique, folder placement is immaterial.
-- Columns are GSI name, tag path
--
insert into TagMap values ('A-BALER-TEMP-LAB-DATA','[]LabData/VFU/A-BALER-TEMP-LAB-DATA/value','DOUBLE');
insert into TagMap values ('AB-BALER-TEMP-LAB-DATA','[]LabData/VFU/AB_BALER_TEMP/value','DOUBLE');
insert into TagMap values ('AB-BALER-VOL-FTNIR-DATA','[]LabData/VFU/AB-BALER-VOL-FTNIR-DATA/value','DOUBLE');
insert into TagMap values ('AB-BALER-VOL-FTNIR-SQC-PATH','[]DiagnosticToolkit/DiagnosticToolkit/Connections/ABBalerVolFtnir','STRING');
insert into TagMap values ('AB-BALER-VOL-LAB-DATA','[]LabData/VFU/AB-BALER-VOL-LAB-DATA/value','DOUBLE');
insert into TagMap values ('AB-BALER-VOL-LAB-SQC-PATH','[]DiagnosticToolkit/Connections/ABBalerVolLab','STRING');
insert into TagMap values ('ALKYL_FLOW','[]DiagnosticToolkit/CSTR/VCF262S/value','DOUBLE');
insert into TagMap values ('B-BALER-TEMP-LAB-DATA','[]LabData/VFU/B-BALER-TEMP-LAB-DATA/value','DOUBLE');
insert into TagMap values ('C-BALER-TEMP-LAB-DATA','[]LabData/VFU/C-BALER-TEMP-LAB-DATA/value','DOUBLE');
insert into TagMap values ('C-D-E-BALER-TEMP-SQC','[]DiagnosticToolkit/Connections/CDEBalerTemp','STRING');
insert into TagMap values ('C-RX_GRD_PATH-GDA','[]DiagnosticToolkit/Connections/CRxGrd','STRING');
insert into TagMap values ('C101-ETHYLENE','[]Tags/C101_ETHYLENE','DOUBLE');
insert into TagMap values ('C2-LAB-DATA','[]LabData/RLA3/C2-LAB-DATA/value','DOUBLE');
insert into TagMap values ('C2-LAB-DATA-FOR-R1-NLC','[]LabData/RLA3/C2-LAB-DATA-FOR-R1-NLC/value','DOUBLE');
insert into TagMap values ('C2_FLOW','[]DiagnosticToolkit/CSTR/VRF002S/value','DOUBLE');
insert into TagMap values ('C2_SQC_TO_C2_CSTR-GDA','[]DiagnosticToolkit/Connections/C2SqcToC2Cstr','STRING');
insert into TagMap values ('C3-PURITY-HI','[]Tags/C3_PURITY_HI','DOUBLE');
insert into TagMap values ('C3CONV_LOW_LIMIT','[]Site/CRx/C3CONV_LOW_LIMIT','DOUBLE');
insert into TagMap values ('C3_CONVERSION','[]DiagnosticToolkit/CRx/VRG521Z/value','DOUBLE');
insert into TagMap values ('C6_RX_FEED-VNB','[]DiagnosticToolkit/CRx/C6_RX_IN_FEED','DOUBLE');
insert into TagMap values ('C9-GRADE-FLAG','[]DiagnosticToolkit/CSTR/C9-Grade-Flag/value','DOUBLE');
insert into TagMap values ('C9-IN-CRUMB','[]LabData/RLA3/C9-IN-CRUMB/value','DOUBLE');
insert into TagMap values ('C9-LAB-DATA','[]LabData/RLA3/C9-LAB-DATA/value','DOUBLE');
insert into TagMap values ('C9-SPEC-LIMIT-IN-FEED','[]LabData/C9_SPEC_LIMIT_IN_FEED','DOUBLE');
insert into TagMap values ('CA-LAB-DATA','[]LabData/RLA3/CA-LAB-DATA/value','DOUBLE');
insert into TagMap values ('CA-SQC-TO-CRX-GDA','[]DiagnosticToolkit/Connections/CaSqcToCrx','STRING');
insert into TagMap values ('CATEFF_HIGH_LIMIT','[]Site/CRx/CATEFF_HIGH_LIMIT','DOUBLE');
insert into TagMap values ('CATIN-GDA-COUNTER','[]Site/CSTR/CATIN-GDA-COUNTER','INTEGER');
insert into TagMap values ('CATIN-GDA-PROD-ML-ACTIVE','[]Site/CSTR/CATIN-GDA-PROD-ML-ACTIVE','BOOLEAN');
insert into TagMap values ('CAT_EFFICIENCY','[]DiagnosticToolkit/CRx/VRG531Z-1/value','DOUBLE');
insert into TagMap values ('CAT_EFF_HIGH_LIMIT','[]Tags/CAT_EFFICIENCY/highLimit','DOUBLE');
insert into TagMap values ('CAT_IS_IN','[]DiagnosticToolkit/Connections/CatIsIn-a','STRING');
insert into TagMap values ('CAT_IS_IN_PATH-GDA','[]DiagnosticToolkit/Connections/CatIsIn-b','STRING');
insert into TagMap values ('CAT_IS_OUT_PATH-GDA','[]DiagnosticToolkit/Connections/CatIsOut','STRING');
insert into TagMap values ('CAT_PREMIX_TEMP','[]DiagnosticToolkit/CRx/VCT205X/value','DOUBLE');
insert into TagMap values ('CD-BALER-TEMP-LAB-DATA','[]LabData/VFU/CD_BALER_TEMP_LAB_DATA/value','DOUBLE');
insert into TagMap values ('CD-BALER-VOL-FTNIR-DATA','[]LabData/VFU/CD-BALER-VOL-FTNIR-DATA/value','DOUBLE');
insert into TagMap values ('CD-BALER-VOL-FTNIR-SQC-PATH','[]DiagnosticToolkit/Connections/CDBalerVolFtnir','STRING');
insert into TagMap values ('CD-BALER-VOL-LAB-DATA','[]LabData/VFU/CD-BALER-VOL-LAB-DATA/value','DOUBLE');
insert into TagMap values ('CD-BALER-VOL-LAB-SQC-PATH','[]DiagnosticToolkit/Connections/CDBalerVolLab','STRING');
insert into TagMap values ('CD-BALER-VOL-ftnir-DATA','[]LabData/VFU/CD_BALER_VOL_FTNIR_DATA','DOUBLE');
insert into TagMap values ('COLD-START-NLC','[]Site/Parameters/COLD-START-NLC','BOOLEAN');
insert into TagMap values ('CNTR_AVG_TPR_TIP_HT','[]Site/CRx/CNTR_AVG_TPR_TIP_HT/value','DOUBLE');
insert into TagMap values ('CNTR_AVG_TPR_TIP_HT_MAX_DEADBAND','[]Site/CRx/CNTR_AVG_TPR_TIP_HT_MAX_DEADBAND','DOUBLE');
insert into TagMap values ('CNTR_AVG_TPR_TIP_HT_TARGET','[]Site/CRx/CNTR_AVG_TPR_TIP_HT_TARGET','DOUBLE');
insert into TagMap values ('CRX-BLOCK-POLYMER-FLAG','[]DiagnosticToolkit/CRx/CRX-BLOCK-POLYMER-FLAG/value','DOUBLE');
insert into TagMap values ('CRX_HB-3','[]Tags/CRX_HB_3','DOUBLE');
insert into TagMap values ('C_FLYING_SWITCH-GDA-INPUT','[]Site/FlyingSwitch/CRX_FLYING_SWITCH-INPUT','BOOLEAN');
insert into TagMap values ('C_FLYING_SWITCH_OUTPUT','[]DiagnosticToolkit/Connections/CRxFlyingSwitchOutput','STRING');
insert into TagMap values ('C-RX_GRADE_FLAG','[]Site/Parameters/C_RX_GRADE_FLAG','BOOLEAN');
insert into TagMap values ('CS-H2-MTR-IDEAL','[]Site/RLA3/CS-H2-MTR-IDEAL','DOUBLE');
insert into TagMap values ('CS-H2-MTR-USED','[]Site/RLA3/CS-H2-MTR-USED','DOUBLE');
insert into TagMap values ('CS-VRF006','[]Site/RLA3/CS-VRF006','DOUBLE');
insert into TagMap values ('CS-VXL204-CTS','[]Site/RLA3/CS-VXL204-CTS','STRING');
insert into TagMap values ('CS-VRF206','[]Site/RLA3/CS-VRF206','DOUBLE');
insert into TagMap values ('D-BALER-TEMP-LAB-DATA','[]LabData/VFU/D-BALER-TEMP-LAB-DATA/value','DOUBLE');
insert into TagMap values ('DC2-LAB-DATA','[]LabData/RLA3/DC2-LAB-DATA/value','DOUBLE');
insert into TagMap values ('DC9-LAB-DATA','[]LabData/RLA3/DC9-LAB-DATA/value','DOUBLE');
insert into TagMap values ('DML-LAB-DATA','[]LabData/RLA3/DML-LAB-DATA/value','DOUBLE');
insert into TagMap values ('DML-SQC-FLAG','[]LabData/DML_SQC_FLAG','DOUBLE');
insert into TagMap values ('DML-SQC-FLAG','[]Recipe/Local/DML-SQC-FLAG','DOUBLE');
insert into TagMap values ('dr-cool-down-start-time','[]Site/Parameters/DR-COOLDOWN-START','STRING');
insert into TagMap values ('DR-D128A-REGEN-TIME','[]Site/Parameters/DR-128A-REGEN-TIME','DOUBLE');
insert into TagMap values ('DR-D128a-ACT','[]Site/Parameters/DR-128A-ACT','DOUBLE');
insert into TagMap values ('DR-D128B-REGEN-TIME','[]Site/Parameters/DR-128B-REGEN-TIME','DOUBLE');
insert into TagMap values ('DR-D128b-ACT','[]Site/Parameters/DR-128B-ACT','DOUBLE');
insert into TagMap values ('DR-D128C-REGEN-TIME','[]Site/Parameters/DR-128B-REGEN-TIME','DOUBLE');
insert into TagMap values ('DR-D128C-ACT','[]Site/Parameters/DR-128c-ACT','DOUBLE');
insert into TagMap values ('DR-HEATER-BYPASS-ROV-PV','[]Recipe/Local/DR-HEATER-BYPASS-ROV-PV','DOUBLE');
insert into TagMap values ('DR-HEATER-IN-ROV-PV','[]Recipe/Local/DR-HEATER-IN-ROV-PV','DOUBLE');
insert into TagMap values ('DR-MOISTURE-REMOVAL-START-TIME','[]Recipe/Local/DR-DRIER-REMOVAL-TIME','DOUBLE');
insert into TagMap values ('DR-PE124B-PV','[]Site/Parameters/DR-PE124b-PV','DOUBLE');
insert into TagMap values ('E202-BYPASS-DELTA-TIME','[]Recipe/Local/BYPASS-DELTA-TIME','DOUBLE');
insert into TagMap values ('E-BALER-TEMP-LAB-DATA','[]LabData/VFU/E-BALER-TEMP-LAB-DATA/value','DOUBLE');
insert into TagMap values ('E-BALER-VOL-FTNIR-DATA','[]LabData/VFU/E-BALER-VOL-FTNIR-DATA/value','DOUBLE');
insert into TagMap values ('E-BALER-VOL-FTNIR-SQC-PATH','[]DiagnosticToolkit/Connections/EBalerVolFtnir','STRING');
insert into TagMap values ('E-BALER-VOL-LAB-DATA','[]LabData/VFU/E-BALER-VOL-LAB-DATA/value','DOUBLE');
insert into TagMap values ('E-BALER-VOL-LAB-SQC-PATH','[]DiagnosticToolkit/Connections/EBalerVolLab','STRING');
insert into TagMap values ('EM-COLD-STICK-RX-OUTLET-TEMP-MONITOR-BLOCK-1','[]Site/VFU/COLDSTICK-OUTLET-TEMP-MONITOR','STRING');
insert into TagMap values ('EM-MONITOR-COLDSTICK-DCS-SETPOINTS-BLOCK','[]Site/VFU/COLDSTICK-DCS-SETPOINT','STRING');
insert into TagMap values ('EM-GDA-LOGICAL-VARIABLE-XXX-2','[]Site/VFU/VFU_FREEZER_SWITCH_REMINDER','BOOLEAN');
insert into TagMap values ('EM-GDA-LOGICAL-VARIABLE-XXX-293','[]Site/Parameters/LogicalVariable293','STRING');
insert into TagMap values ('EM-GDA-SYMBOLIC-VARIABLE-XXX-291','[]Site/Parameters/SymbolicVariable291','STRING');
insert into TagMap values ('EM-GDA-SYMBOLIC-VARIABLE-XXX-292','[]Site/Parameters/SymbolicVariable292','STRING');
insert into TagMap values ('EM-GDA-SYMBOLIC-VARIABLE-XXX-429','[]Site/CRx/ML-GRAVITY-TIMER-STATE','BOOLEAN');
insert into TagMap values ('EM-GDA-SYMBOLIC-VARIABLE-XXX-4651','[]Site/Parameters/SymbolicVariable4651','STRING');
insert into TagMap values ('EM-MONITOR-COLDSTICK-DCS-SETPOINTS-BLOCK','[]Site/DCS-SETPOINTS/monitorColdstick','STRING');    --- found in s88
insert into TagMap values ('EM-MONITOR-MODE','[]Site/Tags/EM-MONITOR-MODE','BOOLEAN');
insert into TagMap values ('FREEZER-SAMPLE-SWITCH','[]Site/VFU/FREEZER-SAMPLE-SWITCH','BOOLEAN');
insert into TagMap values ('FRNT_AVG_C2','[]DiagnosticToolkit/CRx/CRX_HB-9/value','DOUBLE');
insert into TagMap values ('FRNT_AVG_C2_HIGH_LIMIT','[]Site/CRx/FRNT_AVG_C2_HIGH_LIMIT','DOUBLE');
insert into TagMap values ('FRNT_AVG_C2_NOT_HIGH_PATH-GDA','[]DiagnosticToolkit/Connections/FrntAvgC2NotHigh','STRING');
insert into TagMap values ('FRNT_AVG_C2_TARGET','[]Site/CRx/FRNT_AVG_C2_TARGET','DOUBLE');
insert into TagMap values ('FRNT_FEED_DIFF','[]Site/CRx/FRNT_FEED_DIFF/value','DOUBLE');
insert into TagMap values ('FRNT_LNGTH','[]DiagnosticToolkit/CRx/CRX_HB-8/value','DOUBLE');
insert into TagMap values ('FRNT_LNGTH_ABOVE_SP_PATH-GDA','[]DiagnosticToolkit/Connections/FrntLngthAboveSP','STRING');
insert into TagMap values ('FRNT_LNGTH_BELOW_SETPOINT_TO_SF-4-GDA','[]DiagnosticToolkit/Connections/FrntLngthBelowSetpointSF4','STRING');
insert into TagMap values ('FRNT_LNGTH_HIGH_LIMIT','[]Site/CRx/FRNT_LNGTH_HIGH_LIMIT','DOUBLE');
insert into TagMap values ('FRNT_LNGTH_LOW_LIMIT','[]Tags/FRNT_LNGTH/lowLimit','DOUBLE');
insert into TagMap values ('FRNT_LNGTH_LOW_LIMIT','[]Site/CRx/FRNT_LNGTH_LOW_LIMIT','DOUBLE');
insert into TagMap values ('FRNT_LNGTH_SHORT_TO_MOONEY_LOGIC-GDA','[]DiagnosticToolkit/Connections/FrntLngthShortToMooneyLogic','STRING');
insert into TagMap values ('FRNT_LNGTH_TARGET','[]Site/CRx/FRNT_LNGTH_TARGET','DOUBLE');
insert into TagMap values ('FRNT_SDSTRM_MAX_DIFF','[]Site/CRx/FRNT_SDSTRM_MAX_DIFF','DOUBLE');
insert into TagMap values ('FRNT_TPR_TIP_HT_DIFF','[]Site/CRx/FRNT_TPR_TIP_HT_DIFF/value','DOUBLE');
insert into TagMap values ('FRNT_TPR_TIP_HT_HIGH_LIMIT','[]Site/CRx/FRNT_TPR_TIP_HT_HIGH_LIMIT','DOUBLE');
insert into TagMap values ('FRNT_TPR_TIP_HT_MAX_DIFF','[]Site/CRx/FRNT_TPR_TIP_HT_MAX_DIFF','DOUBLE');
insert into TagMap values ('FS-C3STRM_C2','[]DiagnosticToolkit/CRx/FS-C3STRM-C2','DOUBLE');    --- found in s88
insert into TagMap values ('FS-C3STRM_C3','[]DiagnosticToolkit/CRx/FS-C3STRM-C3','DOUBLE');    --- found in s88
insert into TagMap values ('FS-C3STRM_C2o','[]DiagnosticToolkit/CRx/FS-C3STRM-C2o','DOUBLE');    --- found in s88
insert into TagMap values ('FS-C3STRM_C3o','[]DiagnosticToolkit/CRx/FS-C3STRM-C3o','DOUBLE');    --- found in s88
insert into TagMap values ('g2-latency-time','[]Site/G2-LATENCY-TIME','DOUBLE');
insert into TagMap values ('GAIN_AVG-C2_MAIN-C3','[]Site/CRx/AVG-C2-MAIN-C3-GAIN','DOUBLE');
insert into TagMap values ('GAIN_CAT_C3','[]Site/CRx/CAT-C3-GAIN','DOUBLE');
insert into TagMap values ('GAIN_CAT_TEMP','[]Site/CRx/CAT-TEMP-GAIN','DOUBLE');
insert into TagMap values ('GAIN_CNTR-TPR-TIP_SS-C3-to-C2','[]Site/CRx/CNTR-TPR_TIP-SS-C3-C2-GAIN','DOUBLE');
insert into TagMap values ('GAIN_FRNT-C2_MAIN-FD','[]Site/CRx/FRNT-C2-MAIN-FD-GAIN','DOUBLE');
insert into TagMap values ('GAIN_FRNT-C2_SDSTRM-FD','[]Site/CRx/FRNT-C2-SDSTRM-FD-GAIN','DOUBLE');
insert into TagMap values ('GAIN_LNGTH_TEMP','[]Site/CRx/LNGTH-TEMP-GAIN','DOUBLE');
insert into TagMap values ('GAIN_ML_TEMP','[]Site/CRx/ML-TEMP-GAIN','DOUBLE');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-490','[]DiagnosticToolkit/Connections/ConnectionPost490','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-491','[]DiagnosticToolkit/Connections/ConnectionPost491','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-492','[]DiagnosticToolkit/Connections/ConnectionPost492','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-568','[]DiagnosticToolkit/Connections/ConnectionPost568a','STRING');
insert into TagMap values ('GDL-DATA-PATH-CONNECTION-POST-XXX-569','[]DiagnosticToolkit/Connections/ConnectionPost569','STRING');
insert into TagMap values ('GDL-INFERENCE-PATH-CONNECTION-POST-XXX-488','[]DiagnosticToolkit/Connections/ConnectionPost488','STRING');
insert into TagMap values ('GDL-INFERENCE-PATH-CONNECTION-POST-XXX-489','[]DiagnosticToolkit/Connections/ConnectionPost489','STRING');
insert into TagMap values ('GDL-INFERENCE-PATH-CONNECTION-POST-XXX-568','[]DiagnosticToolkit/Connections/ConnectionPost568b','STRING');
insert into TagMap values ('MAIN-C2','[]Site/CRx/MAIN-C2','DOUBLE');
insert into TagMap values ('MAIN-C3','[]Site/CRx/MAIN-C3','DOUBLE');
insert into TagMap values ('MAX_CNTR_TPR_TIP_DELTA_FM_AVG','[]Site/CRx/MAX_CNTR_TPR_TIP_DELTA_FM_AVG/value','DOUBLE');
insert into TagMap values ('MIXTEE_IN_USE_0_EAST_1_WEST','[]DiagnosticToolkit/CRx/VCT205X-2/value','DOUBLE');
insert into TagMap values ('MLR-GRADE-FLAG','[]Recipe/Local/MLR-GRADE-FLAG','DOUBLE');
insert into TagMap values ('MLR-LAB-DATA','[]LabData/RLA3/MLR-LAB-DATA/value','DOUBLE');
insert into TagMap values ('ML_HIGH-GDA','[]DiagnosticToolkit/Connections/MlHigh','STRING');
insert into TagMap values ('ML_LOW_PATH-GDA','[]DiagnosticToolkit/Connections/MlLow','STRING');
insert into TagMap values ('MOONEY-LAB-DATA','[]LabData/RLA3/MOONEY-LAB-DATA','DOUBLE');
insert into TagMap values ('MOONEY_RESET_TIME_FOR_SF-3','[]Site/CRX/MOONEY_RESET_TIME_FOR_SF-3/value','DOUBLE');
insert into TagMap values ('MOONEY_SQC_TO_CSTR_MOONEY-GDA','[]DiagnosticToolkit/Connections/MooneySqcToCstrMooney','STRING');
insert into TagMap values ('MY-CONNECTION-POST','[]DiagnosticToolkit/Connections/MyConnectionPost','STRING');
insert into TagMap values ('OK_TO_FETCH_SC-4_DATA-GDA','[]Site/CRx/OK-TO-FETCH-SC4','BOOLEAN');
insert into TagMap values ('OIL-GRADE-FLAG','[]DiagnosticToolkit/CSTR/OIL-GRADE-FLAG','DOUBLE');
insert into TagMap values ('OIL-LAB-DATA','[]LabData/RLA3/OIL-LAB-DATA/value','DOUBLE');
insert into TagMap values ('POLYSPLIT-DATA','[]LabData/RLA3/POLYSPLIT-DATA-SQC','DOUBLE');
insert into TagMap values ('POLYSPLIT-DATA','[]LabData/RLA3/POLYSPLIT-DATA','DOUBLE');
insert into TagMap values ('POLYSPLIT-SQC-FLAG','[]Recipe/Local/POLYSPLIT-SQC-FLAG','DOUBLE');
insert into TagMap values ('POLY_RATE_CHANGE-GDA-INPUT','[]Site/RateChange/CRX_RATE_CHANGE-INPUT','BOOLEAN');
insert into TagMap values ('POLY_RATE_CHANGE_OUTPUT','[]DiagnosticToolkit/Connections/PolyRateChangeOutput','STRING');
insert into TagMap values ('PREMIX_LINE_DATA_OK-GDA','[]Site/CRx/PREMIX_LINE_DATA_OK ','STRING');
insert into TagMap values ('PREMIX_LINE_FRESH-GDA-PARAMETER','[]Site/CRx/PREMIX_LINE_FRESH-PARAMETER','STRING');
insert into TagMap values ('PREMIX_LINE_FRESH-PATH-GDA','[]DiagnosticToolkit/Connections/PremixLineFresh','STRING');
insert into TagMap values ('PREMIX_TEMP_AVAIL_PATH-GDA','[]DiagnosticToolkit/Connections/PremixTempAvail','STRING');
insert into TagMap values ('PREMIX_TEMP_CHG_PERMITTED-PATH-GDA','[]DiagnosticToolkit/Connections/PremixTempChgPermitted','STRING');
insert into TagMap values ('PREMIX_TEMP_HIGH_LIMIT','[]Site/CRx/PREMIX_TEMP_HIGH_LIMIT','DOUBLE');
insert into TagMap values ('PREMIX_TEMP_LESS_THAN_MAX_PATH-GDA','[]DiagnosticToolkit/Connections/PremixTempLessThanMax','STRING');
insert into TagMap values ('PROD-CA-SQC-FLAG','[]Recipe/Local/PROD-CA-SQC-FLAG','DOUBLE');
insert into TagMap values ('PROD-ML-LAB-DATA','[]LabData/PROD_ML_LAB_DATA/highLImit','DOUBLE');
insert into TagMap values ('PROD-ML-LAB-DATA','[]LabData/RLA3/PROD-ML-LAB-DATA/value','DOUBLE');
insert into TagMap values ('PROD-ML-VFU-OK','[]Site/VFU/Prod_ML-VFU-OK','BOOLEAN');
insert into TagMap values ('RATE_CHANGE_OUTPUT','[]DiagnosticToolkit/Connections/RateChangeOutput','STRING');
insert into TagMap values ('RLA3-CURRENT-GRADE','[]DiagnosticToolkit/CSTR/RLA3-Current-Grade/value','DOUBLE');
insert into TagMap values ('rla3-run-hours','[]Site/RLA3-RUN-HOURS','DOUBLE');
insert into TagMap values ('RX-ML-OK-PATH-GDA','[]DiagnosticToolkit/Connections/RxMlOk','STRING');
insert into TagMap values ('RX_CONFIGURATION','[]DiagnosticToolkit/CSTR/RX-CONFIGURATION/value','DOUBLE');
insert into TagMap values ('SD-STRM-C2_FLOW','[]DiagnosticToolkit/CRX/VRF202S','DOUBLE');
insert into TagMap values ('SDSTRM-1','[]DiagnosticToolkit/CRx/SDSTRM-1','DOUBLE');
insert into TagMap values ('SDSTRM-2','[]DiagnosticToolkit/CRx/SDSTRM-2','DOUBLE');
insert into TagMap values ('SDSTRM-3','[]DiagnosticToolkit/CRx/SDSTRM-3','DOUBLE');
insert into TagMap values ('SDSTRM-4','[]DiagnosticToolkit/CRx/SDSTRM-4','DOUBLE');
insert into TagMap values ('SDSTRM-5','[]DiagnosticToolkit/CRx/SDSTRM-5','DOUBLE');
insert into TagMap values ('SDSTRM-6','[]DiagnosticToolkit/CRx/SDSTRM-6','DOUBLE');
insert into TagMap values ('SDSTRM-C2','[]DiagnosticToolkit/CRx/SDSTRM-C2','DOUBLE');
insert into TagMap values ('SDSTRM-C3C2-RATIO','[]DiagnosticToolkit/CRx/VRF503R-2','DOUBLE');
insert into TagMap values ('SDSTRM_C3-TO-C2_RATIO_HIGH_LIMIT','[]Site/CRx/SDSTRM_C3-TO-C2_RATIO_HIGH_LIMIT','DOUBLE');
insert into TagMap values ('SDSTRM_C3-TO-C2_RATIO_LOW_LIMIT','[]Site/CRx/SDSTRM_C3-TO-C2_RATIO_LOW_LIMIT','DOUBLE');
insert into TagMap values ('SDSTRM_C3C2_RATIO','[]DiagnosticToolkit/Connections/SdstrmC3C2Ratio','STRING');
insert into TagMap values ('SERIES_FLYING_SWITCH-GDA-INPUT','[]Site/FlyingSwitch/SERIES_FLYING_SWITCH-INPUT','BOOLEAN');
insert into TagMap values ('SERIES_FLYING_SWITCH_OUTPUT','[]DiagnosticToolkit/Connections/SeriesFlyingSwitchOutput','STRING');
insert into TagMap values ('SERIES_RATE_CHANGE-GDA-INPUT','[]Site/RateChange/SERIES_RATE_CHANGE-INPUT','BOOLEAN');
insert into TagMap values ('SERIES_RATE_CHANGE_OUTPUT','[]DiagnosticToolkit/Connections/SeriesRateChangeOutput','STRING');
insert into TagMap values ('SERIES_RX_GRADE','[]Site/Parameters/SERIES_RX_GRADE','BOOLEAN');
insert into TagMap values ('SINGLE_FLYING_SWITCH-GDA-INPUT','[]Site/FlyingSwitch/SINGLE_FLYING_SWITCH-INPUT','BOOLEAN');
insert into TagMap values ('SINGLE_FLYING_SWITCH_OUTPUT','[]DiagnosticToolkit/Connections/SingleFlyingSwitchOutput','STRING');
insert into TagMap values ('SINGLE_RATE_CHANGE-GDA-INPUT','[]Site/RateChange/SINGLE_RATE_CHANGE-INPUT','BOOLEAN');
insert into TagMap values ('SINGLE_RATE_CHANGE_OUTPUT','[]DiagnosticToolkit/Connections/SingleRateChangeOutput','STRING');
insert into TagMap values ('SINGLE_RX_GRADE','[]Site/Parameters/SINGLE_RX_GRADE','BOOLEAN');
insert into TagMap values ('SPLIT_FLYING_SWITCH-GDA-INPUT','[]Site/FlyingSwitch/SPLIT_FLYING_SWITCH-INPUT','BOOLEAN');
insert into TagMap values ('SPLIT_FLYING_SWITCH_OUTPUT','[]DiagnosticToolkit/Connections/SplitFlyingSwitchOutput','STRING');
insert into TagMap values ('SPLIT_RATE_CHANGE-GDA-INPUT','[]Site/RateChange/SPLIT_RATE_CHANGE-INPUT','BOOLEAN');
insert into TagMap values ('SPLIT_RATE_CHANGE_OUTPUT','[]DiagnosticToolkit/Connections/SplitRateChangeOutput','STRING');
insert into TagMap values ('SS1_TAPER_TIP_HEIGHT','[]Site/CRx/SS1_TAPER_TIP_HEIGHT/value','DOUBLE');
insert into TagMap values ('SS2_TAPER_TIP_HEIGHT','[]Site/CRx/SS2_TAPER_TIP_HEIGHT/value','DOUBLE');
insert into TagMap values ('STAB-LAB-DATA','[]LabData/RLA3/STAB-LAB-DATA/value','DOUBLE');
insert into TagMap values ('STAB_SQC_TO_CRX-GDA','[]DiagnosticToolkit/Connections/StabSqcToCrx','STRING');
insert into TagMap values ('SWAP_CNTR_FEEDS_TIMER-GDA','[]Site/Parameters/SwapCenterFeedsTimer','STRING');
insert into TagMap values ('UNIFORM_CNTR_TPR_TIPS_PATH-GDA','[]DiagnosticToolkit/Connections/UniformCntrTprTips','STRING');
insert into TagMap values ('VFU-BALER-TEMP-CHK','[]Recipe/Local/VFU-BALER-TEMP-CHK','DOUBLE');
insert into TagMap values ('VFU-CURRENT-GRADE','[]DiagnosticToolkit/CRx/RLA3-Current-Grade','DOUBLE');
insert into TagMap values ('VFU-FTNIR-GRADE','[]Recipe/Local/VFU-FTNIR-GRADE','DOUBLE');
insert into TagMap values ('vrc023_sp','[]Site/CRx/VRC023/sp','DOUBLE');
insert into TagMap values ('VRC062_SP','[]Site/CRx/VRC062/sp','DOUBLE');
insert into TagMap values ('vrc032_sp','[]Site/CRx/VRC032/sp','DOUBLE');
insert into TagMap values ('vrc253_sp','[]Site/CRx/VRC253/sp','DOUBLE');
insert into TagMap values ('vrf214_sp','[]Site/CRx/VRF214/sp','DOUBLE');
insert into TagMap values ('vrf224_sp','[]Site/CRx/VRF224/sp','DOUBLE');
insert into TagMap values ('VRC262_SP','[]Site/CRx/VRC262/sp','DOUBLE');
insert into TagMap values ('the action of the action-button upon the subworkspace of dr-oc-alert-msg','[]Site/DR-OC-ALERT-MSG/action','BOOLEAN');
insert into TagMap values ('the arrow icon-color of the em-setpoint-display-button upon the subworkspace of the item named by console-list [post-index]','[]Site/SETPOINT-DISPLAY-BUTTON/arrowColor','BOOLEAN');
insert into TagMap values ('the btm-message-text of dr-oc-alert-msg','[]Site/DR-OC-ALERT-MSG/bottomText','BOOLEAN');
insert into TagMap values ('the dr-top-temp-reached-timer','[]Site/DRYER-REGEN/topTempReachedTimer','STRING');    --- found in s88
insert into TagMap values ('the message-text of FS-DOWNLOAD-REMINDER-OPERATOR-DISPLAY','[]DiagnosticToolkit/CRx/FS-DOWNLOAD-REMONDER-OPERATOR-DISPLAY','STRING');    --- found in s88
insert into TagMap values ('the cast-time-to-closed of CATOUT-RECIPE-STATUS','[]Site/CATOUT-RECIPE-STATUS/castTimeToCLosed','STRING');    --- found in s88
insert into TagMap values ('the mid-temp of the driers named by drier-to-regen','[]Site/DRYER-REGEN/midTemp','STRING');    --- found in s88
insert into TagMap values ('the outlet-temp of the driers named by drier-to-regen','[]Site/DRYER-REGEN/outletTemp','STRING');    --- found in s88
insert into TagMap values ('the irg-time-to-closed of CATOUT-RECIPE-STATUS','[]Site/CATOUT-RECIPE-STATUS/irgTimeToClosed','STRING');    --- found in s88
insert into TagMap values ('the rx-temp of RX-RECIPE','[]Site/RX-RECIPE/rxTemp','STRING'); 
insert into TagMap values ('the oil-time-to-closed of CATOUT-RECIPE-STATUS','[]Site/CATOUT-RECIPE-STATUS/oilTimeToCLosed','STRING');    --- found in s88
insert into TagMap values ('the lower_limit of DC9-LAB-DATA]','[]LabData/RLA3/DC9-LAB-DATA/lowerLimit','DOUBLE');
insert into TagMap values ('the upper_limit of DC9-LAB-DATA]','[]LabData/RLA3/DC9-LAB-DATA/upperLimit','DOUBLE');
insert into TagMap values ('the state of cat-and-c2-is-in-gda','[]Site/CAT-AND-C2/state','STRING');
insert into TagMap values ('the state of opr-no-reply','[]Site/OPR-NO-REPLY/state','STRING');
insert into TagMap values ('the state of opr-stop','[]Site/OPR-STOP/state','STRING');
insert into TagMap values ('the state of done','[]Site/DONE/state','STRING');
insert into TagMap values ('the subworkspace of UIR-TABLES','[]Site/UIR-TABLES','STRING');
insert into TagMap values ('the target-value of e204-level-ok-conditional','[]Site/E204-LEVEL_OK','BOOLEAN');
insert into TagMap values ('the target-value of e204-level-not-ok-conditional','[]Site/E204-LEVEL_NOT_OK','BOOLEAN');
insert into TagMap values ('the top-message-text of dr-oc-alert-msg','[]Site/DR-OC-ALERT-MSG/topText','BOOLEAN');
insert into TagMap values ('the uir-button-label of UIRdata','[]Site/UIR-DATA/buttonLabel','STRING');
insert into TagMap values ('the uir-date of UIRdata','[]Site/UIR-DATA/date','STRING');
insert into TagMap values ('the uir-email-config of UIRdata','[]Site/UIR-DATA/emailConfig','STRING');
insert into TagMap values ('the uir-form-name of UIRdata','[]Site/UIR-DATA/formName','STRING');
insert into TagMap values ('the uir-identifier of UIRdata','[]Site/UIR-DATA/identifier','STRING');
insert into TagMap values ('the uir-incident-start of UIRdata','[]Site/UIR-DATA/incidentStart','STRING');
insert into TagMap values ('the uir-operator-post of UIRdata','[]Site/UIR-DATA/operatorPost','STRING');
insert into TagMap values ('the uir-quality-18 of UIRdata','[]Site/UIR-DATA/quality18','STRING');
insert into TagMap values ('the uir-root-15 of UIRdata','[]Site/UIR-DATA/root15','STRING');
insert into TagMap values ('the uir-summary of UIRdata','[]Site/UIR-DATA/summary','STRING');
insert into TagMap values ('the uir-title of UIRdata','[]Site/UIR-DATA/title','STRING');
insert into TagMap values ('the uir-unit of UIRdata','[]Site/UIR-DATA/unit','STRING');
insert into TagMap values ('the uir-window-name of UIRdata','[]Site/UIR-DATA/windowName','STRING');
insert into TagMap values ('[the bad-value of ALKYL_FLOW]','[]DiagnosticToolkit/CSTR/VCF262S/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of C2_FLOW]','[]DiagnosticToolkit/CSTR/VRF002S/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of C3_CONVERSION]','[]DiagnosticToolkit/CRx/VRG521Z/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of C9-GRADE-FLAG]','[]DiagnosticToolkit/CSTR/C9-Grade-Flag/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of CAT_EFFICIENCY]','[]DiagnosticToolkit/CRx/VRG531Z-1/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of CAT_PREMIX_TEMP]','[]DiagnosticToolkit/CRx/VCT205X-2/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of CNTR_AVG_TPR_TIP_HT]','[]Site/CRx/CNTR_AVG_TPR_TIP_HT/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of CRX-BLOCK-POLYMER-FLAG]','[]DiagnosticToolkit/CRx/CRX-BLOCK-POLYMER-FLAG/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of FRNT_AVG_C2]','[]DiagnosticToolkit/CRx/CRX_HB-9/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of FRNT_FEED_DIFF]','[]Site/CRx/FRNT_FEED_DIFF/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of FRNT_LNGTH]','[]DiagnosticToolkit/CRx/CRX_HB-8/badValue','BOOLAB-BALER-VOL-FTNIR-DATAEAN');
insert into TagMap values ('[the bad-value of FRNT_TPR_TIP_HT_DIFF]','[]Site/CRx/FRNT_TPR_TIP_HT_DIFF/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of MAX_CNTR_TPR_TIP_DELTA_FM_AVG]','[]Site/CRx/MAX_CNTR_TPR_TIP_DELTA_FM_AVG/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of MIXTEE_IN_USE_0_EAST_1_WEST]','[]DiagnosticToolkit/CRx/VCT2052/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of MOONEY_RESET_TIME_FOR_SF-3]','[]Site/CRX/MOONEY_RESET_TIME_FOR_SF-3/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of OIL-GRADE-FLAG]','[]DiagnosticToolkit/CSTR/OIL-GRADE-FLAG/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of RLA3-CURRENT-GRADE]','[]DiagnosticToolkit/CSTR/RLA3-CURRENT-GRADE/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of RX_CONFIGURATION ]','[]DiagnosticToolkit/CSTR/RX-CONFIGURATION/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of RX_CONFIGURATION]','[]DiagnosticToolkit/CSTR/RX-CONFIGURATION/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of SD-STRM-C2_FLOW]','[]DiagnosticToolkit/CRX/VRF202S/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of SDSTRM-C3C2-RATIO]','[]DiagnosticToolkit/CRX/VRF503R-2/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of SS1_TAPER_TIP_HEIGHT]','[]Site/CRx/SS1_TAPER_TIP_HEIGHT/badValue','BOOLEAN');
insert into TagMap values ('[the bad-value of SS2_TAPER_TIP_HEIGHT]','[]Site/CRx/SS2_TAPER_TIP_HEIGHT/badValue','BOOLEAN');
insert into TagMap values ('[the c2-c3-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/C2C3','DOUBLE');
insert into TagMap values ('[the c2-c9-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/C2C9','DOUBLE');
insert into TagMap values ('[the c2-cat-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/C2Cat','DOUBLE');
insert into TagMap values ('[the c2-h2-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/C2H2','DOUBLE');
insert into TagMap values ('[the c2-r2c3-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/C2R2C3','DOUBLE');
insert into TagMap values ('[the dc2-r1c3-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/Dc2R1C3','DOUBLE');
insert into TagMap values ('[the dc2-r2c3-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/Dc2R2C3','DOUBLE');
insert into TagMap values ('[the denb-r1enb-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DenbR1Enb','DOUBLE');
insert into TagMap values ('[the denb-r2enb-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DenbR2Enb','DOUBLE');
insert into TagMap values ('[the dml-h2-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DmlH2','DOUBLE');
insert into TagMap values ('[the dml-nh3-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DmlNh3','DOUBLE');
insert into TagMap values ('[the dml-r1c2-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DmlR1C2','DOUBLE');
insert into TagMap values ('[the dml-r1c3-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DmlR1C3','DOUBLE');
insert into TagMap values ('[the dml-r1enb-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DmlR1Enb','DOUBLE');
insert into TagMap values ('[the dml-r2c2-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DmlR2C2','DOUBLE');
insert into TagMap values ('[the dml-r2enb-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/DmlR2Enb','DOUBLE');
insert into TagMap values ('[the enb-c3-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/EnbC3','DOUBLE');
insert into TagMap values ('[the enb-cat-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/EnbCat','DOUBLE');
insert into TagMap values ('[the enb-enb-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/EnbEnb','DOUBLE');
insert into TagMap values ('[the enb-h2-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/EnbH2','DOUBLE');
insert into TagMap values ('[the depth-at-outlet of crx-zone-1]','[]Site/CRx/ZONE1/DepthAtOutlet','DOUBLE');
insert into TagMap values ('[the depth-at-outlet of crx-zone-2]','[]Site/CRx/ZONE2/DepthAtOutlet','DOUBLE');
insert into TagMap values ('[the height-at-inlet of crx-zone-2]','[]Site/CRx/ZONE2/HeightAtInlet','DOUBLE');
insert into TagMap values ('[the height-at-inlet of crx-zone-3]','[]Site/CRx/ZONE3/HeightAtInlet','DOUBLE');
insert into TagMap values ('[the sdstrm-monomer-flow of crx-zone-2]','[]Site/CRx/ZONE2/SdstrmMonomerFlow','DOUBLE');
insert into TagMap values ('[the sdstrm-monomer-flow of crx-zone-3]','[]Site/CRx/ZONE3/SdstrmMonomerFlow','DOUBLE');
insert into TagMap values ('[the lower_limit of MOONEY-LAB-DATA]','[]LabData/RLA3/MOONEY-LAB-DATA/lowerLimit','DOUBLE');
insert into TagMap values ('[the lower_limit of STAB-LAB-DATA]','[]LabData/RLA3/STAB-LAB-DATA/lowerLimit','DOUBLE');
insert into TagMap values ('[the ml-c3-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/MlC3','DOUBLE');
insert into TagMap values ('[the ml-cat-gain of current-running-gains]','[]Site/CSTR/CURRENT-GAINS/MlCat','DOUBLE');
insert into TagMap values ('[the ml-h2-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/MlH2','DOUBLE');
insert into TagMap values ('[the mlr-al-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/MlrAl','DOUBLE');
insert into TagMap values ('[the mlr-c3-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/MlrC3','DOUBLE');
insert into TagMap values ('[the mlr-cat-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/MlrCat','DOUBLE');
insert into TagMap values ('[the mlr-h2-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/MlrH2','DOUBLE');
insert into TagMap values ('[the mlr-nh3-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/MlrNh3','DOUBLE');
insert into TagMap values ('[the mlr-temp-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/MlrTemp','DOUBLE');
insert into TagMap values ('[the ps-r1c2-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/PsR1C2','DOUBLE');
insert into TagMap values ('[the ps-r2c2-gain of current-running-gains]', '[]Site/CSTR/CURRENT-GAINS/PsR2C2','DOUBLE');
insert into TagMap values ('[the standard-deviation of A-BALER-TEMP-LAB-DATA]','[]LabData/VFU/A-BALER-TEMP-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of AB-BALER-VOL-ftnir-DATA]','[]LabData/VFU/AB-BALER-VOL-FTNIR-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of AB-BALER-VOL-lab-DATA]','[]LabData/VFU/AB-BALER-VOL-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of B-BALER-TEMP-LAB-DATA]','[]LabData/VFU/B-BALER-TEMP-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of C-BALER-TEMP-LAB-DATA]','[]LabData/VFU/C-BALER-TEMP-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of C2-LAB-DATA]','[]LabData/RLA3/C2-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of CA-LAB-DATA]','[]LabData/RLA3/CA-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of CD-BALER-VOL-ftnir-DATA]','[]LabData/VFU/CD-BALER-VOL-FTNIR-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of CD-BALER-VOL-lab-DATA]','[]LabData/VFU/CD-BALER-VOL-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of D-BALER-TEMP-LAB-DATA]','[]LabData/VFU/D-BALER-TEMP-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of DC2-LAB-DATA]','[]LabData/DC2_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of DC2-LAB-DATA]','[]LabData/RLA3/DC2-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of DML-LAB-DATA]','[]LabData/DML_LAB_DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of DML-LAB-DATA]','[]LabData/RLA3/DML-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of Dc9-lab-data]','[]LabData/RLA3/DC9-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of E-BALER-TEMP-LAB-DATA]','[]LabData/VFU/E-BALER-TEMP-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of E-BALER-VOL-ftnir-DATA]','[]LabData/E_BALER_VOL_FTNIR-DATA/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of E-BALER-VOL-ftnir-DATA]','[]LabData/VFU/E-BALER-VOL-FTNIR-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of E-BALER-VOL-lab-DATA]','[]LabData/VFU/E-BALER-VOL-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of MLR-LAB-DATA]','[]LabData/RLA3/MLR-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of MOONEY-LAB-DATA]','[]LabData/RLA3/MOONEY-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of OIL-LAB-DATA]','[]LabData/RLA3/OIL-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of POLYSPLIT-DATA]','[]LabData/RLA3/POLYSPLIT-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of PROD-ML-LAB-DATA]','[]LabData/RLA3/PROD-ML-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of STAB-LAB-DATA]','[]LabData/RLA3/STAB-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the standard-deviation of c9-lab-data]','[]LabData/RLA3/C9-LAB-DATA-SQC/standardDeviation','DOUBLE');
insert into TagMap values ('[the target of A-BALER-TEMP-LAB-DATA]','[]LabData/VFU/A-BALER-TEMP-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of AB-BALER-TEMP-LAB-DATA]','[]LabData/AB_BALER_TEMP/target','DOUBLE');
insert into TagMap values ('[the target of AB-BALER-VOL-ftnir-DATA]','[]LabData/VFU/AB-BALER-VOL-FTNIR-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of AB-BALER-VOL-lab-DATA]','[]LabData/VFU/AB-BALER-VOL-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of B-BALER-TEMP-LAB-DATA]','[]LabData/VFU/B-BALER-TEMP-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of C-BALER-TEMP-LAB-DATA]','[]LabData/VFU/C-BALER-TEMP-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of C2-LAB-DATA]','[]LabData/RLA3/C2-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of CA-LAB-DATA]','[]LabData/RLA3/CA-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of CD-BALER-VOL-ftnir-DATA]','[]LabData/VFU/CD-BALER-VOL-FTNIR-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of CD-BALER-VOL-lab-DATA]','[]LabData/VFU/CD-BALER-VOL-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of D-BALER-TEMP-LAB-DATA]','[]LabData/VFU/D-BALER-TEMP-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of DC2-LAB-DATA]','[]LabData/RLA3/DC2-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of DML-LAB-DATA]','[]LabData/RLA3/DML-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of Dc9-lab-data]','[]LabData/RLA3/DC9-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of E-BALER-TEMP-LAB-DATA]','[]LabData/VFU/E-BALER-TEMP-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of E-BALER-VOL-ftnir-DATA]','[]Tags/VFU/E-BALER-VOL-FTNIR-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of E-BALER-VOL-lab-DATA]','[]LabData/VFU/E-BALER-VOL-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of MLR-LAB-DATA]','[]LabData/RLA3/MLR-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of MOONEY-LAB-DATA]','[]LabData/RLA3/MOONEY-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of OIL-LAB-DATA]','[]LabData/RLA3/OIL-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of POLYSPLIT-DATA]','[]LabData/RLA3/POLYSPLIT-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of PROD-ML-LAB-DATA]','[]LabData/RLA3/PROD-ML-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of STAB-LAB-DATA]','[]LabData/RLA3/STAB-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the target of c9-lab-data]','[]LabData/RLA3/C9-LAB-DATA-SQC/target','DOUBLE');
insert into TagMap values ('[the time-of-most-recent-grade-change of rla3-run-hours]','[]Tags/RLA3_RUN_HOURS/gradeChangeTime','INTEGER');
insert into TagMap values ('[the time-of-most-recent-recommendation-implementation of frnt_short_use_temp-gda]','[]Tags/FRNT_SHORT_USE_TEMP_GDA/implementationTime','INTEGER');
insert into TagMap values ('[the top-message-text of dr-oc-alert-msg]','[]DR/OC-ALERT-MSG','STRING');
insert into TagMap values ('[the _result of heat-soak-timeout]','[]DR/HEAT-SOAK-TIMEOUT/result','BOOLEAN');
insert into TagMap values ('[the upper_limit of MOONEY-LAB-DATA]','[]LabData/RLA3/MOONEY-LAB-DATA/upperLimit','DOUBLE');
insert into TagMap values ('ca_filtered_value','[]LabData/RLA3/CA-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('cast-disposition-entry','[]Site/CAST-DISPOSITION-ENTRY','DOUBLE');
insert into TagMap values ('cs-recipe-downloaded','[]Vistalon/RLA3/CS-RECIPE-DOWNLOADED','BOOLEAN');
insert into TagMap values ('cs-prestick-checklist-complete','[]Vistalon/RLA3/CS-PRESTICK-CHECKLIST-COMPLETE','BOOLEAN');
insert into TagMap values ('cs-sqc-gains-reviewed','[]Vistalon/RLA3/CS-SQC-GAINS-REVIEWED','BOOLEAN');
insert into TagMap values ('cs-sqc-limits-reviewed','[]Vistalon/RLA3/CS-SQC-LIMITS-REVIEWED','BOOLEAN');
insert into TagMap values ('d20-service-status','[]Site/SERVICE-STATUS/D20','DOUBLE');
insert into TagMap values ('d20a-service-status','[]Site/SERVICE-STATUS/D20a','DOUBLE');
insert into TagMap values ('d20b-service-status','[]Site/SERVICE-STATUS/D20b','DOUBLE');
insert into TagMap values ('dc2_filtered_value','[]LabData/RLA3/DC2-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('denb_filtered_value','[]LabData/RLA3/DENB-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('dml_filtered_value','[]LabData/RLA3/DML-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('enb_filtered_value','[]LabData/RLA3/ENB-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('ethylene_filtered_value','[]LabData/RLA3/ETHYLENE-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('mlr_filtered_value','[]LabData/RLA3/MLR-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('mooney_filtered_value','[]LabData/RLA3/MOONEY-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('oc-alert-start-exe','[]Site/Parametera/OC-ALERT_START','BOOLEAN');
insert into TagMap values ('oil_filtered_value','[]LabData/RLA3/OIL-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('polysplit_filtered_value','[]LabData/RLA3/POLYSPLIT-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('s88-rc-main-c2-rate-ramper','[]Site/S88-RC-MAIN/C2-RATE-RAMPER','DOUBLE');
insert into TagMap values ('s88-rc-r2-c2-rate-ramper','[]Site/S88-RC-MAIN/C2-R2-RAMPER','DOUBLE');
insert into TagMap values ('s88-rc-poly-rate','[]Site/RC/POLY_RATE','BOOLEAN');
insert into TagMap values ('s88-rx-rcp-alkyl-and-sweep','[]Site/S88-RX-RCP/ALKYL-SWEEP','DOUBLE');
insert into TagMap values ('s88-rx-rcp-alkyl-conc','[]Site/S88-RX-RCP/ALKYL-CONC','DOUBLE');
insert into TagMap values ('s88-rx-rcp-ca-efficiency','[]Site/S88-RX-RCP/CA-EFFICIENCY','DOUBLE');
insert into TagMap values ('s88-rx-rcp-cast-conc','[]Site/S88-RX-RCP/CAST-CONC','DOUBLE');
insert into TagMap values ('s88-rx-rcp-cat2d901','[]Site/S88-RX-RCP/CAT2D901','DOUBLE');
insert into TagMap values ('s88-rx-rcp-c3strm_c2','[]Site/S88-RX-RCP/C3STRM-C2','DOUBLE');
insert into TagMap values ('s88-rx-rcp-c3strm_c2o','[]Site/S88-RX-RCP/C3STRM-C2O','DOUBLE');
insert into TagMap values ('s88-rx-rcp-c3strm_c3','[]Site/S88-RX-RCP/C3STRM-C3','DOUBLE');
insert into TagMap values ('s88-rx-rcp-c3strm_c3o','[]Site/S88-RX-RCP/C3STRM-C3O','DOUBLE');
insert into TagMap values ('s88-rx-rcp-crx-mix-tee-flow','[]Site/S88-RX-RCP/CRX-MIX-TEE-FLOW','DOUBLE');
insert into TagMap values ('s88-rx-rcp-etoh-conc','[]Site/S88-RX-RCP/ETOH-CONC','DOUBLE');
insert into TagMap values ('s88-rx-rcp-etoh-sweep','[]Site/S88-RX-RCP/ETOH-SWEEP','DOUBLE');
insert into TagMap values ('s88-rx-rcp-mw-alykl','[]Site/S88-RX-RCP/MW-ALYKL','DOUBLE');
insert into TagMap values ('s88-rx-rcp-mw-van','[]Site/S88-RX-RCP/MW-VAN','DOUBLE');
insert into TagMap values ('s88-rx-rcp-nh3-sweep','[]Site/S88-RX-RCP/NH3-SWEEP','DOUBLE');
insert into TagMap values ('s88-rx-rcp-oil-flag','[]Site/S88-RX-RCP/OIL-FLAG','BOOLEAN');
insert into TagMap values ('s88-rx-rcp-r1-heat-of-rx','[]Site/S88-RX-RCP/R1-HEAT-OF-RX','DOUBLE');
insert into TagMap values ('s88-rx-rcp-ss1-nozzle','[]Site/S88-RX-RCP/SS1-NOZZLE','DOUBLE');
insert into TagMap values ('s88-rx-rcp-ss2-nozzle','[]Site/S88-RX-RCP/SS2-NOZZLE','DOUBLE');
insert into TagMap values ('s88-rx-rcp-ss3-nozzle','[]Site/S88-RX-RCP/SS3-NOZZLE','DOUBLE');
insert into TagMap values ('s88-rx-rcp-ss4-nozzle','[]Site/S88-RX-RCP/SS4-NOZZLE','DOUBLE');
insert into TagMap values ('s88-rx-rcp-ss5-nozzle','[]Site/S88-RX-RCP/SS5-NOZZLE','DOUBLE');
insert into TagMap values ('s88-rx-rcp-ss6-nozzle','[]Site/S88-RX-RCP/SS6-NOZZLE','DOUBLE');
insert into TagMap values ('s88-rx-rcp-van-sweep','[]Site/S88-RX-RCP/VAN-SWEEP','DOUBLE');
insert into TagMap values ('s88-rx-rcp-vocl3-sweep','[]Site/S88-RX-RCP/VOCL3-SWEEP','DOUBLE');
insert into TagMap values ('s88-test-logical-parameter','[]Parameters/s88TestLogicalParameter','BOOLEAN');
insert into TagMap values ('split_feed_grade','[]Site/CSTR/SPLIT_FEED_GRADE','BOOLEAN');
insert into TagMap values ('stab_filtered_value','[]LabData/RLA3/STAB-LAB-DATA/filteredValue','DOUBLE');
insert into TagMap values ('test-8-path-1','[]Site/Parameters/test8Path1','BOOLEAN');
insert into TagMap values ('test-8-path-2','[]Site/Parameters/test8Path2','BOOLEAN');
insert into TagMap values ('temp-prob-for-balers-gda','[]Site/Parameters/BALERS-TEMPERATURE-PROBLEM-NAME','STRING');
-- Miscellaneous Named Objects
insert into TagMap values ('the em-sqc-plot upon the subworkspace of toolkit-console','[]Site/Plots/SqcPlotName','STRING');
