-- Fields aare:  G2 class name, Ignition factory-id, encloses
insert into ClassMap values ('S88-BEGIN','begin-step','false');
insert into ClassMap values ('S88-TIME-DELAY','com.ils.sfc.step.TimedDelayStep','false');
insert into ClassMap values ('S88-ABORT-TASK', 'com.ils.sfc.step.abortStep','false');
insert into ClassMap values ('S88-CALLBACK','action-step','false');
insert into ClassMap values ('S88-CLEAR-QUEUE-TASK','com.ils.sfc.step.clearQueueStep','false');
insert into ClassMap values ('S88-COLLECT-DATA-TASK','com.ils.sfc.step.collectDataStep','false');
insert into ClassMap values ('S88-CONFIRM-CONTROLLER-MODES','com.ils.sfc.step.confirmControllerModesStep','false');
insert into ClassMap values ('S88-MESSAGE-CONSOLE-TASK','com.ils.sfc.step.controlPanelMessageStep','false');
insert into ClassMap values ('S88-REMOVE-BUSY-NOTIFICATION-TASK','com.ils.sfc.step.deleteDelayNotification','false');
insert into ClassMap values ('S88-SHOW-NOTIFICATION-DIALOG-TASK','com.ils.sfc.step.dialogMessageStep','false');
insert into ClassMap values ('S88-ENABLE-OR-DISABLE-COMMAND-TASK','com.ils.sfc.step.enableDisableStep','false');
insert into ClassMap values ('S88-ENCAPSULATION-TASK', 'enclosing-step','true');
insert into ClassMap values ('S88-GET-INPUT-TASK','com.ils.sfc.step.inputStep','false');
insert into ClassMap values ('S88-HOLD-TASK','com.ils.sfc.step.pauseStep','false');
insert into ClassMap values ('S88-LIBRARY-TASK','enclosing-step','false');
insert into ClassMap values ('S88-LIBRARY-CALLER','enclosing-step','false');
insert into ClassMap values ('S88-MANUAL-DATA-ENTRY-TASK','com.ils.sfc.step.dataEntryStep','false');
insert into ClassMap values ('S88-MONITOR-DOWNLOADS-TASK','com.ils.sfc.step.monitorDownloadsStep','false');
insert into ClassMap values ('S88-PV-MONITORING-TASK','com.ils.sfc.step.pvMonitoringStep','false');
insert into ClassMap values ('S88-MESSAGE_QUEUE-TASK','com.ils.sfc.step.queueMessageStep','false');
insert into ClassMap values ('S88-PAUSE-TASK','com.ils.sfc.step.pauseStep','false');
insert into ClassMap values ('S88-POST-BUSY-NOTIFICATION-TASK','com.ils.sfc.step.postDelayNotification','false');
insert into ClassMap values ('S88-PRINT-OR-VIEW-FILE-TASK','com.ils.sfc.step.printFileStep','false');
insert into ClassMap values ('S88-PRINT-WORKSPACE-TASK','com.ils.sfc.step.printWindowStep','false');
insert into ClassMap values ('S88-DATABASE-RAW-QUERY-TASK','com.ils.sfc.step.rawQueryStep','false');
insert into ClassMap values ('S88-REVIEW-DATA-TASK','com.ils.sfc.step.reviewDataStep','false');
insert into ClassMap values ('S88-REVIEW-DATA-WITH-ADVICE-TASK', 'com.ils.sfc.step.reviewDataWithAdviceStep','false');
insert into ClassMap values ('S88-REVIEW-FLOWS-TASK','com.ils.sfc.step.reviewFlowsStep','false');
insert into ClassMap values ('S88-SAVE-RECIPE-DATA-TO-CSV','com.ils.sfc.step.saveDataStep','false');
insert into ClassMap values ('S88-SELECT-INPUT-TASK','com.ils.sfc.step.selectInputStep','false');
insert into ClassMap values ('S88-SET-QUEUE-TASK','com.ils.sfc.step.setQueueStep','false');
insert into ClassMap values ('S88-SHOW-QUEUE-TASK','com.ils.sfc.step.showQueueStep','false');
insert into ClassMap values ('S88-STOP-TASK','com.ils.sfc.step.abortStep','false');
insert into ClassMap values ('S88-DATABASE-SIMPLE-QUERY-TASK','com.ils.sfc.step.simpleQueryStep','false');
insert into ClassMap values ('S88-WRITE-FILE-TASK','com.ils.sfc.step.writeFileStep','false');
insert into ClassMap values ('S88-WRITE-OUTPUTS-TASK','com.ils.sfc.step.writeOutputsStep','false');
insert into ClassMap values ('S88-YES-NO-TASK','com.ils.sfc.step.yesNoStep','false');
insert into ClassMap values ('S88-UNIT-PROCEDURE','enclosing-step','true');
insert into ClassMap values ('S88-OPERATION-PROCEDURE','enclosing-step','true');
