#!/bin/sh
#  Build a database for migration of diagnostics applications. Copy into the migration
#  directory of the project tree.
#
#  -- must be run in the same directory as the insert script.
#
#!/bin/sh
#set -x
DB=conversion.db
BIN=${GIT_REPO}/sfc/migration/mdb
TARGETDIR=${GIT_REPO}/sfc/migration/mdb
mkdir -p ${TARGETDIR}


cd ${TARGETDIR}
rm -f $DB
sqlite3 $DB < ${BIN}/createTables.sql
sqlite3 $DB < ${BIN}/insertAnchorMap.sql
sqlite3 $DB < ${BIN}/insertArguments.sql
sqlite3 $DB < ${BIN}/insertClassMap.sql
sqlite3 $DB < ${BIN}/insertClassProperties.sql
sqlite3 $DB < ${BIN}/insertProperties.sql
sqlite3 $DB < ${BIN}/insertPythonProperties.sql
sqlite3 $DB < ${BIN}/insertPropertyValues.sql
sqlite3 $DB < ${BIN}/insertProcedures.sql
sqlite3 $DB < ${BIN}/insertProcClassMap.sql
sqlite3 $DB < ${BIN}/insertProcGlobals.sql
sqlite3 $DB < ${BIN}/insertProcProperties.sql
sqlite3 $DB < ${BIN}/insertEnumerations.sql
sqlite3 $DB < ${BIN}/insertTags.sql
