#!/bin/sh
#  Build a database for migration of diagnostics applications. Copy into the migration
#  directory of the project tree.
#
#  -- must be run in the same directory as the insert script.
#
#!/bin/sh
#set -x
DB=conversion.db
REPO_ROOT=~/Development/ils/src
BIN=$REPO_ROOT/sfc/migration/mdb
TARGETDIR=$REPO_ROOT/sfc/migration/mdb
mkdir -p ${TARGETDIR}


cd ${TARGETDIR}
rm -f $DB
sqlite3 $DB < ${BIN}/createTables.sql
sqlite3 $DB < ${BIN}/insertClassMap.sql
sqlite3 $DB < ${BIN}/insertProcedures.sql
sqlite3 $DB < ${BIN}/insertProperties.sql
sqlite3 $DB < ${BIN}/insertTags.sql
