#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=~/Development/ils/src/sfc
DIRIN="TestUnitProcedure6"
PROJ="testunitprocedure6.proj"
INDIR="$SFC/xml/ignition/$DIRIN"
OUTFIL=$SFC/xml/$PROJ
rm -f "$OUTFILE"
$SFC/migration/build-project "$INDIR" "$OUTFIL"
