#!/bin/sh
# SFC project build script.
# -- walk the directory hierarchy of the converted
#    tree and create a project file.
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 2 ]
then
    echo "USAGE: build-project <indir> <outfile>"
	exit 2
fi
REPO=${GIT_REPO}
cd $REPO/sfc
SFC=`pwd`
LIB=$REPO/external/lib
JAR=${LIB}/sfc-migration.jar
OUTFIL=$2
OUTFIL=${OUTFIL}.proj
java -cp ${JAR} -Dlog.level=INFO com.ils.sfc.migration.ProjectBuilder $1 ${OUTFIL}
