#!/bin/sh
# SFC project build script.
# -- walk the directory hierarchy of the converted
#    tree and create a project file.
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 2 ]
then
    echo "USAGE: build-project <indir> <outfile>"
	exit 2
fi
REPO=~/Development/ils/src
cd $REPO/sfc
SFC=`pwd`
LIB=$REPO/external/lib
JAR=${LIB}/sfc-migration.jar
# Use for debugging - ruins output file however.
#java -cp ${JAR} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Dlog.level=INFO -Droot.class=APPLICATION com.ils.blt.migration.Migrator ${DB}
java -cp ${JAR} -Dlog.level=INFO com.ils.sfc.migration.ProjectBuilder $1 $2
