#!/bin/sh
# Remove all of the py files from the migration target area.
# We do this to make sure there are no residual files from a 
# previous copy.
#
PROCS=${GIT_REPO}/sfc/migration/procs
rm -rf ${PROCS}/g2
rm -rf ${PROCS}/ignition
