#!/bin/sh
# Remove all of the xml files from the migration target area.
# We do this to make sure there are no residual files from a 
# previous copy.
#
BIN=`pwd`
XML=${GIT_REPO}/sfc/migration/xml
rm -rf ${XML}/g2
rm -rf ${XML}/ignition
#
#  Cleanup obsolete work area also
rm -rf ${GIT_REPO}/sfc/xml
