#!/bin/sh
# Remove all of the xml files from the migration target area.
# We do this to make sure there are no residual files from a 
# previous copy.
#
BIN=`pwd`
PROCS=${GIT_REPO}/sfc/migration/procs
rm -rf ${PROCS}/g2
rm -rf ${PROCS}/python
#
# Cleanup obsolete areas
rm -rf ${GIT_REPO}/sfc/procs
