#!/bin/sh
# Process all of the xml files in the repository "g2" area.
# Save the results in the block storage area for ignition.
#
SFC=$GIT_REPO/sfc
APP=$SFC/migration/convert
INDIR=$SFC/migration/xml/g2/vistalon
PYDIR=$SFC/migration/procs/ignition/vistalon/onstart
OUTDIR=$SFC/migration/xml/ignition/vistalon
mkdir -p $INDIR
mkdir -p $OUTDIR
rm -rf $OUTDIR/*
cd $INDIR
for file in *
do
	echo "Processing $file ..."
    $APP "$INDIR" "$OUTDIR" $PYDIR $file
    exit
done
