#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=${GIT_REPO}/sfc
START="Test-Unit-Procedure-1"
INDIR="$SFC/xml/g2"
OUTDIR=$SFC/xml/ignition
mkdir -p $OUTDIR
rm -rf $OUTDIR/*
$SFC/migration/convert "$INDIR" "$OUTDIR" "$START"
