#!/bin/sh
# Process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
SFC=$GIT_REPO/sfc
APP=$SFC/migration/convert
INDIR=$SFC/migration/xml/g2/Vistalon
OUTDIR=$SFC/migration/xml/ignition/Vistalon
mkdir -p $INDIR
mkdir -p $OUTDIR
rm -rf $OUTDIR/*
cd $INDIR
for dir in *
do
	echo "Processing $dir ..."
    $APP "$INDIR" "$OUTDIR" $dir
done
