#!/bin/sh
#  SFC conversion script
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 4 ]
then
    echo "USAGE: convert <inpath> <outpath> <pypath> <start>"
	exit 2
fi
REPO=${GIT_REPO}
SFC=$REPO/sfc
cd $SFC
LIB=$REPO/external/lib
JAR=${LIB}/sfc-migration.jar
DB=${SFC}/migration/mdb/conversion.db
mkdir -p "$2"
#java -cp ${JAR} -Dlog.level=TRACE com.ils.sfc.migration.Converter ${DB} "$3" "$1" "$2" "$4"
java -cp ${JAR} -Dlog.level=INFO com.ils.sfc.migration.Converter ${DB} "$3" "$1" "$2" "$4"
