#!/bin/sh
# Process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
SFC=$GIT_REPO/sfc
APP=$SFC/migration/convert
INDIR=$SFC/migration/xml/g2/usecase
PYDIR=$SFC/migration/procs/ignition/usecase
OUTDIR=$SFC/migration/xml/ignition/usecase
mkdir -p $INDIR
mkdir -p $OUTDIR
rm -rf $OUTDIR/*
cd $INDIR
for file in *
do
	echo "Processing $file ..."
    $APP "$INDIR" "$OUTDIR" $PYDIR $file
done
