#!/bin/sh
# Copy XML export files from svn into our project
# for viewing in Eclipse. Clean out irrelevant directories.
#
SVNUC=${SVN_REPO}/EMChemicals/G2Artifacts/Sequential\ Control/UnitTests
SVNVIST="${SVN_REPO}/EMChemicals/Migration/Vistalon/Exports From G2/SequentialControl"
XML=${GIT_REPO}/sfc/migration/xml
mkdir -p $XML/g2/usecase
mkdir -p $XML/g2/vistalon
mkdir -p $XML/ignition
cp -a "${SVNUC}"/* $XML/g2/usecase
cd "${SVNVIST}"
for dir in *
do
   if [ -d $dir ]
   then
      cd $dir
      cd SFCs
      echo `pwd`
      mkdir -p $XML/g2/vistalon/$dir
      cp -a * $XML/g2/vistalon/$dir
      cd "${SVNVIST}"
   fi
done
# Clean up the non-xml
find ${XML}/g2 -type f ! -name "*.xml" -exec rm {}  \; 
rm -r `find ${XML}/g2 -type d -name Diagrams`  2&>/dev/null
rm -r `find ${XML}/g2 -type d -name diagrams`  2&>/dev/null
rm -r `find ${XML}/g2 -type d -name callbacks`  2&>/dev/null
rm `find ${XML}/g2 -type f -name "*.csv"`  2&>/dev/null
# Clean up unwanted charts
cd ${XML}
rm -rf g2/vistalon/VISTALON-UNIT-PROCEDURE/*OFFLINE-OPERATION
