#!/bin/sh
# Copy G2 procedure exports from svn into our project
# for processing with conversion tools. Segregate "normal"
# versus those destined to be "onstart"
#
BIN=`pwd`
SVN=${SVN_REPO}/EMChemicals/G2Artifacts/Sequential\ Control
REPO=${GIT_REPO}/sfc/procs
mkdir -p $REPO/g2/onstart
mkdir -p $REPO/g2/normal
mkdir -p $REPO/python/onstart
mkdir -p $REPO/python/normal
cp -a "${SVN}"/UnitTests/*/callbacks/*.txt $REPO/g2/onstart
cp -a "${SVN}"/Vistalon/*/callbacks/*.txt $REPO/g2/normal
