#!/bin/sh
# Copy G2 procedure exports from svn into our project
# for processing with conversion tools. Segregate "normal"
# versus those destined to be "onstart"
#
BIN=`pwd`
SVN="${SVN_REPO}/EMChemicals/G2Artifacts/Sequential Control"
PROCS=${GIT_REPO}/sfc/migration/procs
mkdir -p $PROCS/g2/onstart
mkdir -p $PROCS/g2/normal
mkdir -p $PROCS/python/onstart
mkdir -p $PROCS/python/normal
#cp -a "${SVN}"/UnitTests/*/callbacks/*.txt $REPO/g2/onstart
#cp -a "${SVN}"/Vistalon/*/callbacks/*.txt $REPO/g2/normal
for fil in "${SVN}"/UnitTests/*/callbacks/*.txt
do
	name=`basename "$fil"`
	cat "$fil"| sed -e 's/if DEBUG-MODE then post/trace/' > ${PROCS}/g2/onstart/$name
done
