#!/bin/sh
# Copy XML export files from svn into our project
# for viewing in Eclipse. Clean out irrelevant directories.
#
BIN=`pwd`
SVN=~/Development/ils/svn/EMChemicals/G2Artifacts/Sequential\ Control
REPO=~/Development/ils/src/sfc/xml
mkdir -p $REPO/g2/
mkdir -p $REPO/ignition
cp -a "${SVN}"/* $REPO/g2
# Clean up the non-xml
find ${REPO}/g2 -type f ! -name "*.xml" -exec rm {}  \; 
rm -r `find ${REPO}/g2 -type d -name Diagrams`  2&>/dev/null
rm -r `find ${REPO}/g2 -type d -name diagrams`  2&>/dev/null
rm -r `find ${REPO}/g2 -type d -name callbacks`  2&>/dev/null
