#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=~/Development/ils/src/sfc
PROJ="testunitprocedure2.proj"
OUTFIL=$SFC/xml/$PROJ
rm -f "$OUTFILE"
$SFC/migration/debug-project "$OUTFIL"
