#!/bin/sh
# SFC project debug script.
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 1 ]
then
    echo "USAGE: debug-project <inpath>"
	exit 2
fi
REPO=${GIT_REPO}
SFC=${GIT_REPO}/sfc
LIB=${GIT_REPO}/external/lib
JAR=${LIB}/sfc-migration.jar
cat $1 | java -cp ${JAR} -Dlog.level=INFO com.ils.sfc.migration.ProjectDebugger $1 
