#!/bin/sh
# SFC project debug script.
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 1 ]
then
    echo "USAGE: debug-project <inpath>"
	exit 2
fi
REPO=~/Development/ils/src
cd $REPO/sfc
SFC=`pwd`
LIB=$REPO/external/lib
JAR=${LIB}/sfc-migration.jar
# Use for debugging - ruins output file however.
#cat $1 | java -cp ${JAR} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Dlog.level=INFO -Droot.class=APPLICATION com.ils.blt.migration.Migrator ${DB}
cat $1 | java -cp ${JAR} -Dlog.level=INFO com.ils.sfc.migration.ProjectDebugger $1 
