#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=~/Development/ils/src/sfc
DIRIN="Test Diagram"
INDIR="$SFC/xml/g2/$DIRIN"
OUTDIR=$SFC/xml/ignition
mkdir -p $OUTDIR
rm -rf $OUTDIR/*
$SFC/migration/migrate "$INDIR" "$OUTDIR"
