#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=~/Development/ils/src/sfc
DIRIN="Test Diagram"
DIROUT=""
INDIR="$SFC/xml/g2/$DIRIN"
OUTDIR=$SFC/xml/ignition/$DIROUT
mkdir -p $OUTDIR
$SFC/migration/migrate "$INDIR" "$OUTDIR"
