#!/bin/sh
# Process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
SFC=~/Development/ils/src/sfc
APP=$SFC/migration/migrate
INDIR=$SFC/xml/g2
OUTDIR=$SFC/xml/ignition
mkdir -p $INDIR
mkdir -p $OUTDIR
rm -rf $OUTDIR/*
cd $INDIR
for dir in *
do
	echo "Processing $dir ..."
    $APP "$INDIR" "$OUTDIR" "$dir"
done
