#!/bin/sh
# Clear existing artifacts (with the exception of those checked into
# the 'git' repository. Copy freshly exported artifacts from the 
# svn repository. Process both sfc and procedure exports.
# I haven't figured out how to capture output in a log file.
#
SFC=${GIT_REPO}/sfc
MIGRATION=${SFC}/migration
LOG=${MIGRATION}/migration_results.log
rm -f $LOG

${MIGRATION}/process-vistalon all 
