#!/bin/sh
#  Data migration conversion script
# -- options for root.class: APPLICATION, DIAGRAM
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 2 ]
then
    echo "USAGE: migrate <inpath> <outpath>"
	exit 2
fi
REPO=~/Development/ils/src
cd $REPO/blt
SFC=`pwd`
LIB=$REPO/external/lib
JAR=${LIB}/sfc-migration.jar
DB=${SFC}/migration/mdb/conversion.db
# Use for debugging - ruins output file however.
#cat $1 | java -cp ${JAR} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Dlog.level=INFO -Droot.class=APPLICATION com.ils.blt.migration.Migrator ${DB}
cat $1 | java -cp ${JAR} -Dlog.level=INFO -Droot.class=APPLICATION com.ils.sfc.migration.Migrator ${DB} > $2
