#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=~/Development/ils/src/sfc
START="Test-Unit-Procedure-2"
INDIR="$SFC/xml/g2"
OUTDIR=$SFC/xml/ignition
mkdir -p $OUTDIR
rm -rf $OUTDIR/*
$SFC/migration/migrate "$INDIR" "$OUTDIR" "$START"
