#!/bin/sh
#  TAg migration conversion script. Output is directed to stdout
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 0 ]
then
    echo "USAGE: mktags"
	exit 2
fi
REPO=~/Development/ils/src
cd $REPO/sfc
SFC=`pwd`
LIB=$REPO/external/lib
JAR=${LIB}/sfc-migration.jar
DB=${SFC}/migration/mdb/conversion.db
# Use for debugging - ruins output file however.
#cat ${MIGRATION}/$FIL-g2.json | java -cp ${JAR} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000 -Dlog.level=INFO -Droot.class=APPLICATION com.ils.blt.migration.Migrator ${DB} > ${MIGRATION}/$FIL.json
java -cp ${JAR} -Dlog.level=INFO com.ils.sfc.migration.TagMigrator ${DB} 
