#!/bin/sh
#  TAg migration conversion script. Output is directed to stdout
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 0 ]
then
    echo "USAGE: mktags"
	exit 2
fi
SFC=${GIT_REPO}/sfc
LIB=${GIT_REPO}/external/lib
JAR=${LIB}/sfc-migration.jar
DB=${SFC}/migration/mdb/conversion.db
java -cp ${JAR} -Dlog.level=INFO com.ils.sfc.migration.TagMigrator ${DB} 
