#!/bin/sh
# Process only those charts that are in the "vetted" area.
# There is no need to translate G2 procedures or convert G2 charts.
#   -- create project files from the vetted XML and translated procedures
#
SFC=$GIT_REPO/sfc
INDIR="$SFC/migration/xml/vetted/vistalon"
OUTDIR=$SFC/migration/projects/Vistalon
mkdir -p $OUTDIR
rm -rf $OUTDIR/*

cd $SFC/migration
#
#
cd $INDIR
for PROJ in *
do
    INFIL=${INDIR}/$PROJ
    OUTFIL=${OUTDIR}/$PROJ
    rm -f $OUTFIL
    $SFC/migration/build-project "$INFIL" "$OUTFIL"
done
