#!/bin/sh
# Start-to-finish processing of unit tests.
#   -- copy from svn repository
#   -- translate all relevant procedures
#   -- convert from G2 xml to Ignition xml
#   -- create project files from the converted XML and translated procedures
#
SFC=$GIT_REPO/sfc
PYDIR=$GIT_REPO/xom-python/XOM_Python/src/scripts/usecase
OUTDIR=$SFC/migration/projects/usecase
mkdir -p $OUTDIR
rm -rf $OUTDIR/*

cd $SFC/migration
./clear-procs usecase
./clear-xml usecase
./copy-procs 
./copy-xml
#
# Translare the procedures
echo "========================== Procedure Translation ============================"
./translate-usecases all
cd $SFC/migration/procs/ignition/usecase
cp -a * $PYDIR
cd $SFC/migration
#
# Convert the XML 
echo "========================== Chart Translation ============================"
./convert-usecases all
echo "==========================      Complete         ============================"

#
#  We currently expect 16 use cases
#
for TESTNO in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
do
    DIRIN="TestUnitProcedure${TESTNO}"
    INDIR="$SFC/migration/xml/ignition/usecase/$DIRIN"
    PROJ="testunitprocedure${TESTNO}"
    OUTFIL=${OUTDIR}/$PROJ
    rm -f $OUTFIL
    $SFC/migration/build-project "$INDIR" "$OUTFIL"
done
