#!/bin/sh
# Start-to-finish processing of unit tests.
#   -- copy from svn repository
#   -- translate all relevant procedures
#   -- convert from G2 xml to Ignition xml
#   -- create project files from the converted XML and translated procedures
#
SFC=$GIT_REPO/sfc
OUTDIR=$SFC/migration/projects/UnitTests
mkdir -p $OUTDIR
rm -rf $OUTDIR/*

cd $SFC/migration
./clear-procs
./clear-xml
./copy-procs
./copy-xml
#
# Translare the procedures
./translate-usecases
#
# Convert the XML 
./convert-usecases

#
#  We currently expect 12 use cases
#
for TESTNO in 1 2 3 4 5 6 7 8 9 10 11 12
do
    DIRIN="TestUnitProcedure${TESTNO}"
    INDIR="$SFC/migration/xml/ignition/UnitTests/$DIRIN"
    PROJ="testunitprocedure${TESTNO}.proj"
    OUTFIL=${OUTDIR}/$PROJ
    rm -f $OUTFIL
    $SFC/migration/build-project "$INDIR" "$OUTFIL"
done
