#!/bin/sh
# Process the .txt files in the usecase "g2" area.
# If the argument is "all", then all the files are processed.
# If the argument is "next" then the current file is processed
# and deleted. Then the next file is processed.
#
# We start with raw G2 exports. Translate, then save the
# results in the procedure storage area for ignition.
#
OPT="one"
if [ $# -gt 0 ]
then
    OPT=$1
fi
SFC=${GIT_REPO}/sfc
APP=${SFC}/migration/translate-onstart
mkdir -p ${SFC}/migration/procs/g2/usecase/onstart
cd ${SFC}/migration/procs/g2/usecase/onstart
OUTDIR=${SFC}/migration/procs/ignition/usecase/onstart
DIR=`${SFC}/migration/pwd2`
echo 'Rob, DIR is' $DIR
for fil in *.txt
do
    if [ -f $DIR/$fil ]
    then
	   echo "Processing $fil..."
       $APP $DIR/$fil $OUTDIR
    else
       continue
    fi
	if [ $OPT == "all" ]
	then
		continue
	elif [ $OPT == "one" ]
	then
		exit
	else
		rm $DIR/$fil
		OPT="one"
	fi
done
