#!/bin/sh
# Process the .txt files in the vistalon "g2" area.
# If the argument is "all", then all the files are processed.
# If the argument is "next" then the current file is processed
# and deleted. Then the next file is processed.
#
# We start with raw G2 exports. Translate, then save the
# results in the procedure storage area for ignition.
#
OPT="one"
if [ $# -gt 0 ]
then
    OPT=$1
fi
SFC=${GIT_REPO}/sfc
# ======================= OnStop ====================
APP=${SFC}/migration/translate-onstop
mkdir -p ${SFC}/migration/procs/g2/vistalon/onstop
cd ${SFC}/migration/procs/g2/vistalon/onstop
OUTDIR=${SFC}/migration/procs/ignition/vistalon/onstop
DIR=${SFC}/migration
echo 'Rob, dir is' $DIR
for fil in *.txt
do
    if [ -f $DIR/$fil ]
    then
	   echo "Processing $fil..."
       $APP $DIR/$fil $OUTDIR
    else
       continue
    fi
	if [ $OPT == "all" ]
	then
		continue
	elif [ $OPT == "one" ]
	then
		exit
	else
		rm $DIR/$fil
		OPT="one"
	fi
done
# ======================= OnStart ====================
APP=${SFC}/migration/translate-onstart
mkdir -p ${SFC}/migration/procs/g2/vistalon/onstart
cd ${SFC}/migration/procs/g2/vistalon/onstart
OUTDIR=${SFC}/migration/procs/ignition/vistalon/onstart
DIR=${SFC}/migration
for fil in *.txt
do
    if [ -f $DIR/$fil ]
    then
	   echo "Processing $fil..."
       $APP $DIR/$fil $OUTDIR
    else
       continue
    fi
	if [ $OPT == "all" ]
	then
		continue
	elif [ $OPT == "one" ]
	then
		exit
	else
		rm $DIR/$fil
		OPT="one"
	fi
done
