#!/bin/sh
# Process all of the json files in the repository "g2" area.
# Save the results in the json storate area for ignition.
#
SFC=~/Development/ils/repo/sfc
APP=${SFC}/migration/translate
cd ${SFC}/migration/samples
for fil in *.txt
do
	echo "Processing $fil..."
    $APP $fil
done
