#!/bin/sh
#  Procedure migration script. File is in the local directory
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 2 ]
then
    echo "USAGE: translate <file> <outdir>"
	exit 2
fi
REPO=${GIT_REPO}
SFC=$REPO/sfc
cd $SFC
LIB=$REPO/external/lib
JAR=${LIB}/g2-translation.jar
DB=${SFC}/migration/mdb/conversion.db
OUTDIR=$2
mkdir -p ${OUTDIR}
echo ${DB}
#java -cp ${JAR} -Dlog.level=TRACE com.ils.python.translation.G2ProcedureTranslator $1 ${OUTDIR} ${DB} 
java -cp ${JAR} -Dlog.level=INFO com.ils.python.translation.G2ProcedureTranslator $1 ${OUTDIR} ${DB} 
