#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=~/Development/ils/src/sfc
FIL=EM-S88-C-RX-MAT-ENRGY-BALANCE-COLD-STICK.txt
DIR=${SFC}/migration/samples
${SFC}/migration/translate $DIR/$FIL
