#!/bin/sh
#  Procedure migration script
# -- options for log.level:  INFO,DEBUG,TRACE
#
if [ $# -lt 1 ]
then
    echo "USAGE: translate <file>"
	exit 2
fi
REPO=${GIT_REPO}
SFC=$REPO/sfc
cd $SFC
LIB=$REPO/external/lib
JAR=${LIB}/g2-translation.jar
DB=${SFC}/migration/mdb/conversion.db
OUTDIR=${SFC}/procs/python/onstart
mkdir -p ${OUTDIR}
#cat $1 | java -cp ${JAR} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000  -Dprocedure.package= -Dprocedure.variant=sfc.onstart -Dlog.level=DEBUG com.ils.python.translation.G2ProcedureTranslator ${OUTDIR} ${DB} 
cat $1 | java -cp ${JAR} -Dprocedure.package= -Dprocedure.variant=sfc.onstart -Dlog.level=DEBUG com.ils.python.translation.G2ProcedureTranslator ${OUTDIR} ${DB} 
