#!/bin/sh
# Process all of the .txt files in the repository "g2" area.
# These are the raw G2 exports. Translate, then save the
# results in the procedure storage area for ignition.
#
set -x
SFC=${GIT_REPO}/sfc
APP=${SFC}/migration/translate-onstart
mkdir -p ${SFC}/migration/procs/g2/vistalon/onstart
cd ${SFC}/migration/procs/g2/vistalon/onstart
OUTDIR=${SFC}/migration/procs/ignition/vistalon/onstart
DIR=`pwd`
for fil in *.txt
do
	echo "Processing $fil..."
    $APP $DIR/$fil $OUTDIR
	exit
done
