#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=${GIT_REPO}/sfc
DIRIN="TestUnitProcedure2"
PROJ="testunitprocedure2.proj"
INDIR="$SFC/xml/ignition/UnitTests/$DIRIN"
OUTFIL=$SFC/xml/ignition/UnitTests/$PROJ
rm -f "$OUTFILE"
$SFC/migration/build-project "$INDIR" "$OUTFIL"
