#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=${GIT_REPO}/sfc
DIRIN="TestUnitProcedure5"
PROJ="testunitprocedure5.proj"
INDIR="$SFC/xml/ignition/$DIRIN"
OUTFIL=$SFC/xml/$PROJ
rm -f "$OUTFILE"
$SFC/migration/build-project "$INDIR" "$OUTFIL"
