#!/bin/sh
#  Use this version when debugging a single file.
#
SFC=${GIT_REPO}/sfc
START="Test-Unit-Procedure-6"
INDIR="$SFC/xml/g2/UnitTests"
OUTDIR=$SFC/xml/ignition/UnitTests
mkdir -p $OUTDIR
rm -rf $OUTDIR/*
$SFC/migration/convert "$INDIR" "$OUTDIR" "$START"
