#!/bin/sh
# Process a specific use case. Skip translating.
#   -- convert from G2 xml to Ignition xml
#   -- create project files from the converted XML and translated procedures
#
if [ $# = 0 ]
then
    echo "USAGE: process-usecase <uc#>"
	exit 1
fi
UC=$1
SFC=$GIT_REPO/sfc
PYDIR=${SFC}/migration/procs/ignition/usecase

cd $SFC/migration
#
# Translate the procedures
#echo "========================== Procedure Translation ============================"
#./translate-usecases all
#cd $SFC/migration/procs/ignition/usecase
#cp -a * $PYDIR
#cd $SFC/migration
#
# Convert the XML 
echo "========================== Chart Translation    ============================"
APP=${SFC}/migration/convert
INDIR=${SFC}/migration/xml/g2/usecase
OUTDIR=$SFC/migration/xml/ignition/usecase
OUTNAME="Test-Unit-Procedure-$UC"
mkdir -p ${OUTDIR}$DIRNAME
rm -rf ${OUTDIR}/$OUTNAME
${APP} "$INDIR" "$OUTDIR" "$PYDIR" $OUTNAME

echo "========================= Project Generation   ============================"
APP=${SFC}/migration/build-project
INDIR="$SFC/migration/xml/ignition/usecase/TestUnitProcedure$UC"
OUTDIR=$SFC/migration/projects/usecase
mkdir -p ${OUTDIR}
PROJ="testunitprocedure${UC}"
OUTFIL=${OUTDIR}/$PROJ
rm -fr $OUTFIL
$APP "$INDIR" "$OUTFIL"

echo "==========================      Complete         ============================"
