#!/bin/sh
# Translate a single method used in the use cases
#  - we start from the top and work down testing one-at-a-time
#
MIGRATION=${GIT_REPO}/sfc/migration
#FIL=PH-TEST-CALLBACK-1.txt
#FIL=S88-CALLBACK-TEMPLATE.txt
#FIL=S88-TEST-GENERIC-CALLBACK.txt
#FIL=S88-TEST-POST-USER-RESPONE.txt
#FIL=S88-TEST-SET-PARAMETER-FALSE.txt
#FIL=TEST-5-CALLBACK-1.txt
#FIL=TEST-5-CALLBACK-2.txt
#FIL=TEST-5-SHARED-CALLBACK.txt
#FIL=TEST-6-CALLBACK.txt
#FIL=TEST-8-INITIALIZATION.txt
FIL=TEST-8-PATH-1.txt
#FIL=TEST-8-PATH-2.txt
#FIL=TEST-8-TIMEOUT-CALLBACK.txt
INDIR=${MIGRATION}/procs/g2/usecase/onstart
cd $INDIR
OUTDIR=${MIGRATION}/procs/ignition/usecase/onstart
${MIGRATION}/translate-onstart $INDIR/$FIL $OUTDIR
