#!/bin/sh
#  Build a database for migration of diagnostics applications. Copy into the migration
#  directory of the project tree.
#
#  -- must be run in the same directory as the insert script.
#
#!/bin/sh
#set -x
DB=lookup.db
REPO_ROOT=~/Development/ils/repo
BIN=$REPO_ROOT/sfc/migration/db
TARGETDIR=$REPO_ROOT/sfc/migration/db
mkdir -p ${TARGETDIR}


cd ${TARGETDIR}
rm -f $DB
sqlite3 $DB < ${BIN}/createTables.sql
sqlite3 $DB < ${BIN}/insertClassMap.sql
sqlite3 $DB < ${BIN}/insertConstants.sql
sqlite3 $DB < ${BIN}/insertProcedureMap.sql
